name: synthex-social
region: nyc3

services:
  - name: web
    github:
      repo: unite-group/unite-hub
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    envs:
      # Supabase
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://lksfwktwtmyznckodsau.supabase.co
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        value: ${SUPABASE_SERVICE_ROLE_KEY}

      # Claude API
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        value: ${ANTHROPIC_API_KEY}

      # NextAuth
      - key: NEXTAUTH_URL
        value: ${NEXTAUTH_URL}
        scope: RUN_AND_BUILD_TIME
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        value: ${NEXTAUTH_SECRET}

      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}
        scope: RUN_AND_BUILD_TIME
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        value: ${GOOGLE_CLIENT_SECRET}

      # Email
      - key: EMAIL_SERVER_HOST
        value: smtp.gmail.com
        scope: RUN_TIME
      - key: EMAIL_SERVER_PORT
        value: "587"
        scope: RUN_TIME
      - key: EMAIL_SERVER_USER
        scope: RUN_TIME
        value: ${EMAIL_SERVER_USER}
      - key: EMAIL_SERVER_PASSWORD
        scope: RUN_TIME
        value: ${EMAIL_SERVER_PASSWORD}
      - key: EMAIL_FROM
        value: ${EMAIL_FROM}
        scope: RUN_TIME

      # Misc
      - key: LOG_LEVEL
        value: info
        scope: RUN_TIME
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME

    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs

databases:
  - name: postgresql-db
    engine: POSTGRESQL
    version: "14"
    production: false

static_sites:
  - name: synthex-static
    source_dir: public

alerts:
  - spec:
      rule: CPU_UTILIZATION
      value: 80
    notifications:
      email:
        - deployment
  - spec:
      rule: MEM_UTILIZATION
      value: 90
    notifications:
      email:
        - deployment

ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: web
