name: unite-hub
region: syd
features:
  - buildpack-stack=ubuntu-22

services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      repo: DisasterRecoveryAgency/Unite-Hub
      branch: main
      deploy_on_push: true
    http_port: 3008
    instance_count: 1
    instance_size_slug: professional-m
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      # Required Core Variables
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3008"

      # Supabase
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://lksfwktwtmyznckodsau.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        type: SECRET
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrc2Z3a3R3dG15em5ja29kc2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MTE1MDksImV4cCI6MjA3ODQ4NzUwOX0.l2KIokOpdMAUFXR9rnFqyIt9zH2hdFX8eHc-oi-UtTw
      - key: SUPABASE_SERVICE_ROLE_KEY
        type: SECRET
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrc2Z3a3R3dG15em5ja29kc2F1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjkxMTUwOSwiZXhwIjoyMDc4NDg3NTA5fQ.o7UTPiEHBK7h2gRvJHifVxp_k990zavnpqG-7RdiN7Q
      - key: DATABASE_URL
        type: SECRET
        value: postgresql://postgres.lksfwktwtmyznckodsau:wOgLede9R4GJzGo8@aws-0-us-east-1.pooler.supabase.com:6543/postgres

      # Anthropic AI
      - key: ANTHROPIC_API_KEY
        type: SECRET
        value: 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

      # NextAuth
      - key: NEXTAUTH_SECRET
        type: SECRET
        value: ejtMMfOz/R/wniUWiSR+9JNh4dyNT+13SlNHuZRMUxM=
      - key: NEXTAUTH_URL
        value: ${APP_URL}

      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        value: 537153033593-ivf845sbehan86fjklf8p617rslnqov4.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        type: SECRET
        value: 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
      - key: GMAIL_CLIENT_ID
        value: 537153033593-ivf845sbehan86fjklf8p617rslnqov4.apps.googleusercontent.com
      - key: GMAIL_CLIENT_SECRET
        type: SECRET
        value: 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

      # Email
      - key: EMAIL_SERVER_HOST
        value: smtp.gmail.com
      - key: EMAIL_SERVER_PORT
        value: "587"
      - key: EMAIL_SERVER_USER
        value: contact@unite-group.in
      - key: EMAIL_SERVER_PASSWORD
        type: SECRET
        value: vulguictdqpqoahx
      - key: EMAIL_FROM
        value: contact@unite-group.in
      - key: SENDGRID_API_KEY
        type: SECRET
        value: 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

      # Stripe
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        value: pk_test_51SK3Z3BY5KEPMwxd73NBxV7AFPamtEy8dbfwPs3ziBMmM4bfP0pQr3IDkaqbhIm5DJ66chBIVLWkwD6SiEAwt5lr007K6qZY7z
      - key: STRIPE_SECRET_KEY
        type: SECRET
        value: sk_test_51SK3Z3BY5KEPMwxdfeioDqPuuDSAt3aH2lZiwfth5Ki7eZB6DquvOLw4BPBENvoBCjjX4UNXdxH2qPBuKutWhXuS0042D7vlG0
      - key: STRIPE_WEBHOOK_SECRET
        type: SECRET
        value: whsec_f8e47035ca94e48ff6d7b140dfae1ac6b5860692ab682a4c44aedfdd7535359d

      # AI Services
      - key: OPENAI_API_KEY
        type: SECRET
        value: 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
      - key: GEMINI_API_KEY
        type: SECRET
        value: AIzaSyBUNpD-NSYTGwLKip3SoSCgZ_s37qCVBB4
      - key: PERPLEXITY_API_KEY
        type: SECRET
        value: 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
      - key: OPENROUTER_API_KEY
        type: SECRET
        value: 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

      # SEO
      - key: DATAFORSEO_API_LOGIN
        value: phill@disasterrecovery.com.au
      - key: DATAFORSEO_API_PASSWORD
        type: SECRET
        value: f1f7eebc972699a7

      # Security
      - key: JWT_SECRET
        type: SECRET
        value: 289423b73d6b61a0657d99b2fc203a48f34fbbf9143afd766e9d79b5e4316eac
      - key: CRON_SECRET
        type: SECRET
        value: 4z+9yl4yBcbERz3Id8szwwSBqwHF71Rw5vtm/6/vowg=
      - key: SEO_CREDENTIAL_ENCRYPTION_KEY
        type: SECRET
        value: c1a98231eb354f9cb46725386c9ec6feceb1dccd17c4406f823d98249fca0fb5

      # App URLs
      - key: NEXT_PUBLIC_BASE_URL
        value: ${APP_URL}
      - key: NEXT_PUBLIC_URL
        value: ${APP_URL}
      - key: NEXT_PUBLIC_APP_URL
        value: ${APP_URL}
