/**
 * Brand Workflow
 * Phase 50: Process branding asset jobs
 */

import { ProductionJob, addJobOutput, updateJobSafety } from './productionEngine';

export async function processBrandJob(
  job: ProductionJob
): Promise<{ success: boolean; error?: string }> {
  try {
    const { input_data } = job;
    const brandType = input_data.brandType || 'guidelines';
    const businessName = input_data.businessName || 'Business';
    const industry = input_data.industry || '';
    const colors = input_data.colors || [];
    const values = input_data.values || [];

    let content = '';
    let title = '';

    switch (brandType) {
      case 'guidelines':
        title = `Brand Guidelines - ${businessName}`;
        content = generateBrandGuidelines(businessName, industry, colors, values);
        break;
      case 'voice':
        title = `Brand Voice Guide - ${businessName}`;
        content = generateBrandVoice(businessName, industry, values);
        break;
      case 'messaging':
        title = `Brand Messaging Framework - ${businessName}`;
        content = generateMessagingFramework(businessName, industry);
        break;
      default:
        title = `Brand Asset - ${businessName}`;
        content = `Brand asset for ${businessName}`;
    }

    await addJobOutput(job.id, job.client_id, {
      outputType: 'markdown',
      title,
      content,
      metadata: {
        brandType,
        businessName,
        industry,
        colors,
        values,
      },
    });

    // Brand assets are high-impact, verify thoroughly
    await updateJobSafety(job.id, 95, [], true);

    return { success: true };
  } catch (error) {
    console.error('Error processing brand job:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Brand generation failed',
    };
  }
}

function generateBrandGuidelines(
  businessName: string,
  industry: string,
  colors: string[],
  values: string[]
): string {
  return `# ${businessName} Brand Guidelines

## Brand Overview
${businessName} operates in the ${industry || 'services'} industry.

## Core Values
${values.length > 0 ? values.map(v => `- ${v}`).join('\n') : '- To be defined'}

## Color Palette
${colors.length > 0 ? colors.map(c => `- ${c}`).join('\n') : '- Primary: To be defined\n- Secondary: To be defined'}

## Typography
- Headings: [Font family]
- Body: [Font family]

## Logo Usage
Guidelines for logo placement and sizing.

## Tone of Voice
Professional yet approachable.

---
*Draft generated by Unite-Hub Production Engine*
`;
}

function generateBrandVoice(
  businessName: string,
  industry: string,
  values: string[]
): string {
  return `# ${businessName} Brand Voice Guide

## Voice Characteristics
- Professional
- Approachable
- Knowledgeable

## Do's
- Use clear, simple language
- Be helpful and informative
- Show expertise without jargon

## Don'ts
- Don't use slang
- Don't make unsubstantiated claims
- Don't be overly casual

## Example Phrases
"We help you achieve..."
"Our approach focuses on..."

---
*Draft generated by Unite-Hub Production Engine*
`;
}

function generateMessagingFramework(businessName: string, industry: string): string {
  return `# ${businessName} Messaging Framework

## Positioning Statement
${businessName} is a ${industry || 'services'} company that [value proposition].

## Key Messages
1. [Primary message]
2. [Secondary message]
3. [Tertiary message]

## Target Audience
[Audience description]

## Differentiators
- [Differentiator 1]
- [Differentiator 2]

---
*Draft generated by Unite-Hub Production Engine*
`;
}

export default { processBrandJob };
