/**
 * Social Media Workflow
 * Phase 50: Process social media content jobs
 */

import { ProductionJob, addJobOutput, updateJobSafety } from './productionEngine';

export async function processSocialJob(
  job: ProductionJob
): Promise<{ success: boolean; error?: string }> {
  try {
    const { input_data } = job;
    const platform = input_data.platform || 'linkedin';
    const postType = input_data.postType || 'post';
    const topic = input_data.topic || '';
    const tone = input_data.tone || 'professional';
    const hashtags = input_data.hashtags || [];

    const content = generateSocialContent(platform, postType, topic, tone, hashtags);
    const title = `${platform.charAt(0).toUpperCase() + platform.slice(1)} ${postType}`;

    await addJobOutput(job.id, job.client_id, {
      outputType: 'text',
      title,
      content,
      metadata: {
        platform,
        postType,
        topic,
        tone,
        hashtags,
        characterCount: content.length,
      },
    });

    // Social content safety check
    const safetyFlags: string[] = [];
    if (content.length > getPlatformLimit(platform)) {
      safetyFlags.push('exceeds_character_limit');
    }

    await updateJobSafety(
      job.id,
      safetyFlags.length === 0 ? 100 : 85,
      safetyFlags,
      true
    );

    return { success: true };
  } catch (error) {
    console.error('Error processing social job:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Social content generation failed',
    };
  }
}

function generateSocialContent(
  platform: string,
  postType: string,
  topic: string,
  tone: string,
  hashtags: string[]
): string {
  const hashtagString = hashtags.length > 0 ? '\n\n' + hashtags.map(h => `#${h}`).join(' ') : '';

  switch (platform) {
    case 'linkedin':
      return `${topic}

Here's why this matters:

• Point 1
• Point 2
• Point 3

What are your thoughts? Share in the comments.${hashtagString}

---
*Draft generated by Unite-Hub*`;

    case 'twitter':
    case 'x':
      return `${topic}

Key takeaway here.${hashtagString}`;

    case 'facebook':
      return `${topic}

[Engaging content about the topic]

What do you think? 👇${hashtagString}`;

    case 'instagram':
      return `${topic}

[Caption content]

.
.
.${hashtagString}`;

    default:
      return `${topic}${hashtagString}

---
*Draft generated by Unite-Hub*`;
  }
}

function getPlatformLimit(platform: string): number {
  const limits: Record<string, number> = {
    twitter: 280,
    x: 280,
    linkedin: 3000,
    facebook: 63206,
    instagram: 2200,
  };
  return limits[platform] || 5000;
}

export default { processSocialJob };
