#!/usr/bin/env node

/**
 * Switch Traffic Script
 *
 * Manages blue-green traffic switching via Nginx upstream configuration.
 * Updates deployment state and reloads Nginx with zero downtime.
 *
 * Usage:
 *   node switch-traffic.mjs --target blue
 *   node switch-traffic.mjs --target green
 */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

// Parse command-line arguments
const args = process.argv.slice(2);
const getArg = (flag, defaultValue) => {
  const index = args.indexOf(flag);
  return index !== -1 && args[index + 1] ? args[index + 1] : defaultValue;
};

const target = getArg('--target', null);

// Configuration
const STATE_FILE = '.deployment-state.json';
const NGINX_CONFIG_PATH = process.platform === 'win32'
  ? 'C:/nginx/conf/upstream.conf'
  : '/etc/nginx/conf.d/upstream.conf';

// Color codes for console output
const colors = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  reset: '\x1b[0m',
};

/**
 * Validate command-line arguments
 */
function validateArgs() {
  if (!target || (target !== 'blue' && target !== 'green')) {
    console.error(`${colors.red}❌ Error: Invalid target. Use --target blue or --target green${colors.reset}`);
    process.exit(1);
  }
}

/**
 * Read deployment state from file
 * @returns {{active: string, standby: string, lastSwitch: string, version: string}}
 */
function readDeploymentState() {
  try {
    if (!fs.existsSync(STATE_FILE)) {
      console.log(`${colors.yellow}⚠️  State file not found. Creating default state...${colors.reset}`);
      const defaultState = {
        active: 'blue',
        standby: 'green',
        lastSwitch: new Date().toISOString(),
        version: '0.0.0',
      };
      fs.writeFileSync(STATE_FILE, JSON.stringify(defaultState, null, 2));
      return defaultState;
    }

    const content = fs.readFileSync(STATE_FILE, 'utf-8');
    return JSON.parse(content);
  } catch (err) {
    console.error(`${colors.red}❌ Error reading state file: ${err.message}${colors.reset}`);
    process.exit(1);
  }
}

/**
 * Write deployment state to file
 * @param {{active: string, standby: string, lastSwitch: string, version: string}} state
 */
function writeDeploymentState(state) {
  try {
    fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
    console.log(`${colors.green}✅ State file updated${colors.reset}`);
  } catch (err) {
    console.error(`${colors.red}❌ Error writing state file: ${err.message}${colors.reset}`);
    process.exit(1);
  }
}

/**
 * Generate Nginx upstream configuration
 * @param {string} activeEnv - Active environment (blue/green)
 * @returns {string} Nginx configuration content
 */
function generateNginxConfig(activeEnv) {
  const bluePort = 3008;
  const greenPort = 3009;
  const activePort = activeEnv === 'blue' ? bluePort : greenPort;

  return `# Auto-generated by blue-green deployment
# Last updated: ${new Date().toISOString()}
# Active environment: ${activeEnv}

upstream unite_hub_backend {
    server localhost:${activePort} max_fails=3 fail_timeout=30s;
}

# Blue environment
upstream unite_hub_blue {
    server localhost:${bluePort};
}

# Green environment
upstream unite_hub_green {
    server localhost:${greenPort};
}
`;
}

/**
 * Write Nginx configuration file
 * @param {string} activeEnv - Active environment (blue/green)
 */
function writeNginxConfig(activeEnv) {
  try {
    const config = generateNginxConfig(activeEnv);
    const configDir = path.dirname(NGINX_CONFIG_PATH);

    // Create directory if it doesn't exist
    if (!fs.existsSync(configDir)) {
      console.log(`${colors.yellow}⚠️  Nginx config directory not found. Creating: ${configDir}${colors.reset}`);
      fs.mkdirSync(configDir, { recursive: true });
    }

    fs.writeFileSync(NGINX_CONFIG_PATH, config);
    console.log(`${colors.green}✅ Nginx configuration updated${colors.reset}`);
  } catch (err) {
    console.error(`${colors.red}❌ Error writing Nginx config: ${err.message}${colors.reset}`);
    process.exit(1);
  }
}

/**
 * Reload Nginx with zero downtime (SIGHUP)
 */
function reloadNginx() {
  try {
    console.log(`${colors.blue}🔄 Reloading Nginx...${colors.reset}`);

    if (process.platform === 'win32') {
      // Windows: nginx -s reload
      execSync('nginx -s reload', { stdio: 'inherit' });
    } else {
      // Unix: systemctl reload nginx or nginx -s reload
      try {
        execSync('systemctl reload nginx', { stdio: 'inherit' });
      } catch {
        // Fallback to direct nginx command
        execSync('nginx -s reload', { stdio: 'inherit' });
      }
    }

    console.log(`${colors.green}✅ Nginx reloaded successfully${colors.reset}`);
  } catch (err) {
    console.error(`${colors.red}❌ Error reloading Nginx: ${err.message}${colors.reset}`);
    console.error(`${colors.yellow}⚠️  You may need to reload Nginx manually with: nginx -s reload${colors.reset}`);
    process.exit(1);
  }
}

/**
 * Verify traffic switch was successful
 * @param {string} targetEnv - Target environment (blue/green)
 * @returns {boolean} Success status
 */
function verifySwitch(targetEnv) {
  try {
    console.log(`${colors.blue}🔍 Verifying traffic switch...${colors.reset}`);

    // Read back the state file
    const state = readDeploymentState();
    if (state.active !== targetEnv) {
      console.error(`${colors.red}❌ Verification failed: State file shows active=${state.active}, expected=${targetEnv}${colors.reset}`);
      return false;
    }

    // Read back the Nginx config
    const config = fs.readFileSync(NGINX_CONFIG_PATH, 'utf-8');
    if (!config.includes(`Active environment: ${targetEnv}`)) {
      console.error(`${colors.red}❌ Verification failed: Nginx config doesn't reflect active environment${colors.reset}`);
      return false;
    }

    console.log(`${colors.green}✅ Verification passed${colors.reset}`);
    return true;
  } catch (err) {
    console.error(`${colors.red}❌ Verification error: ${err.message}${colors.reset}`);
    return false;
  }
}

/**
 * Main execution
 */
function main() {
  console.log(`${colors.blue}═══════════════════════════════════════${colors.reset}`);
  console.log(`${colors.blue}Blue-Green Traffic Switch${colors.reset}`);
  console.log(`${colors.blue}═══════════════════════════════════════${colors.reset}\n`);

  // Validate arguments
  validateArgs();

  console.log(`${colors.blue}Target environment: ${target}${colors.reset}\n`);

  // Read current state
  console.log(`${colors.blue}📖 Reading deployment state...${colors.reset}`);
  const currentState = readDeploymentState();

  console.log(`${colors.blue}Current active: ${currentState.active}${colors.reset}`);
  console.log(`${colors.blue}Current version: ${currentState.version}${colors.reset}`);
  console.log(`${colors.blue}Last switch: ${currentState.lastSwitch}${colors.reset}\n`);

  if (currentState.active === target) {
    console.log(`${colors.yellow}⚠️  Target environment is already active. No switch needed.${colors.reset}`);
    process.exit(0);
  }

  // Update state
  const newState = {
    active: target,
    standby: target === 'blue' ? 'green' : 'blue',
    lastSwitch: new Date().toISOString(),
    version: currentState.version,
  };

  // Write new Nginx configuration
  console.log(`${colors.blue}📝 Updating Nginx configuration...${colors.reset}`);
  writeNginxConfig(target);

  // Reload Nginx
  reloadNginx();

  // Update state file
  console.log(`${colors.blue}💾 Updating deployment state...${colors.reset}`);
  writeDeploymentState(newState);

  // Verify switch
  const verified = verifySwitch(target);

  console.log(`\n${colors.blue}═══════════════════════════════════════${colors.reset}`);
  console.log(`${colors.blue}Traffic Switch Summary${colors.reset}`);
  console.log(`${colors.blue}═══════════════════════════════════════${colors.reset}`);
  console.log(`Status: ${verified ? colors.green + '✅ SUCCESS' : colors.red + '❌ FAILED'}${colors.reset}`);
  console.log(`Previous active: ${currentState.active}`);
  console.log(`New active: ${newState.active}`);
  console.log(`Switch time: ${newState.lastSwitch}`);
  console.log(`${colors.blue}═══════════════════════════════════════${colors.reset}\n`);

  process.exit(verified ? 0 : 1);
}

// Run main function
main();
