import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, CalendarClock, ListChecks } from "lucide-react";
import { getLocalSeoGbpQueueSummary } from "@/lib/seo/localSeoEngineService";

interface SeoGbpQueuePageProps {
  searchParams?: {
    workspaceId?: string;
    status?: string;
  };
}

/**
 * Synthex 2026 Local SEO – GBP Management Queue
 *
 * Reads from `gbp_management_queue` (and the primary
 * `synthex_local_seo_profiles` row for context) to show
 * scheduled and recent Google Business Profile actions.
 *
 * Usage (dev/testing):
 *   /dashboard/seo/gbp-queue?workspaceId=<workspace_uuid>
 */
export default async function SeoGbpQueuePage({
  searchParams,
}: SeoGbpQueuePageProps) {
  const workspaceId = searchParams?.workspaceId;
  const statusFilter = searchParams?.status;

  if (!workspaceId) {
    return (
      <div className="space-y-4">
        <Card className="bg-slate-800/50 border-slate-700">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-white">
              <AlertTriangle className="h-5 w-5 text-amber-400" />
              Workspace required
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-slate-300">
              To view the GBP management queue, open this page with a workspace ID:
            </p>
            <pre className="mt-3 rounded bg-slate-900/60 p-3 text-xs text-slate-200 overflow-x-auto">
              {"/dashboard/seo/gbp-queue?workspaceId=<workspace_uuid>"}
            </pre>
          </CardContent>
        </Card>
      </div>
    );
  }

  const { profile, queue } = await getLocalSeoGbpQueueSummary(workspaceId, {
    status: statusFilter,
    limit: 100,
  });

  const hasData = queue.length > 0;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-white flex items-center gap-2">
          <ListChecks className="h-7 w-7 text-cyan-400" />
          GBP Management Queue
        </h1>
        <p className="text-slate-400 mt-1">
          Inspect scheduled and recent Google Business Profile updates generated by the Local SEO engine.
        </p>
        <p className="text-xs text-slate-500 mt-2">
          Workspace ID: <span className="font-mono">{workspaceId}</span>
        </p>
      </div>

      <Card className="bg-slate-800/50 border-slate-700">
        <CardHeader>
          <CardTitle className="text-white text-base">
            {profile
              ? `Local SEO Profile: ${profile.business_name}`
              : "Local SEO Profile (none configured yet)"}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {profile ? (
            <div className="text-sm text-slate-300 space-y-1">
              <div>
                <span className="font-semibold">Category:</span> {profile.business_category}
              </div>
              <div className="text-xs text-slate-400">
                GBP automation: {profile.gbp_automation_enabled ? "enabled" : "disabled"}
              </div>
            </div>
          ) : (
            <p className="text-sm text-slate-300">
              No Local SEO profile has been created for this workspace yet. The GBP queue will
              still populate as agents schedule actions, but linking it to a profile unlocks
              richer reporting.
            </p>
          )}
        </CardContent>
      </Card>

      <Card className="bg-slate-800/50 border-slate-700">
        <CardHeader>
          <CardTitle className="text-white flex items-center gap-2">
            <CalendarClock className="h-5 w-5" />
            Scheduled & recent GBP actions
          </CardTitle>
        </CardHeader>
        <CardContent>
          {!hasData ? (
            <div className="flex items-start gap-3 rounded-lg bg-slate-900/60 p-4">
              <AlertTriangle className="h-5 w-5 text-amber-400 mt-0.5" />
              <div className="text-sm text-slate-300">
                <p className="font-medium text-slate-100 mb-1">No GBP queue items yet</p>
                <p className="text-slate-400">
                  The <code className="font-mono">gbp_management_queue</code> table is empty for this workspace.
                  Once Synthex begins scheduling Google Business Profile actions, new rows will appear here
                  automatically.
                </p>
              </div>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm">
                <thead>
                  <tr className="border-b border-slate-700 text-slate-400 text-xs uppercase">
                    <th className="py-2 pr-4 text-left">Action</th>
                    <th className="py-2 pr-4 text-left">Status</th>
                    <th className="py-2 pr-4 text-right">Priority</th>
                    <th className="py-2 pr-4 text-left">Scheduled For</th>
                    <th className="py-2 pr-4 text-left">Error</th>
                    <th className="py-2 pr-4 text-left">Created At</th>
                  </tr>
                </thead>
                <tbody>
                  {queue.map((row) => (
                    <tr
                      key={row.id}
                      className="border-b border-slate-800 hover:bg-slate-800/60 transition-colors"
                    >
                      <td className="py-2 pr-4 text-slate-100">{row.action_type}</td>
                      <td className="py-2 pr-4 text-slate-300">{row.status}</td>
                      <td className="py-2 pr-4 text-right text-slate-300">{row.priority}</td>
                      <td className="py-2 pr-4 text-slate-300">
                        {row.scheduled_for || "—"}
                      </td>
                      <td className="py-2 pr-4 text-slate-400 text-xs max-w-xs truncate" title={row.error_message || undefined}>
                        {row.error_message || ""}
                      </td>
                      <td className="py-2 pr-4 text-slate-400 text-xs">
                        {row.created_at}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
