/**
 * Method Catalog
 * Phase 69: Expanded library with ~90-100 visual methods
 */

import { MethodMetadata, createMethodMetadata, registerMethod } from './metadata';

// Initialize all methods
export function initializeMethodCatalog(): void {
  // Hero Visuals (10 methods)
  const heroMethods: MethodMetadata[] = [
    createMethodMetadata({
      id: 'hero_key_art',
      name: 'Key Art Generator',
      description: 'Create primary campaign key art with focal composition',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web', 'email', 'display_ads'],
      complexity: 4,
      brand_personalities: ['bold', 'creative', 'professional'],
      industries: ['entertainment', 'technology', 'fashion'],
      recommended_models: ['nano_banana', 'dalle', 'midjourney'],
      estimated_time_seconds: 90,
      cost_tier: 'high',
      requires_approval: true,
      outputs: ['key_art', 'horizontal_variant', 'vertical_variant'],
      tags: ['hero', 'campaign', 'key_art'],
    }),
    createMethodMetadata({
      id: 'hero_product_shot',
      name: 'Product Hero Shot',
      description: 'Premium product photography-style hero image',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web', 'email', 'print'],
      complexity: 3,
      brand_personalities: ['elegant', 'minimal', 'professional'],
      industries: ['retail', 'beauty', 'technology'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 60,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['product_hero', 'detail_crop'],
      tags: ['product', 'hero', 'ecommerce'],
    }),
    createMethodMetadata({
      id: 'hero_lifestyle',
      name: 'Lifestyle Hero',
      description: 'Lifestyle context hero showing product in use',
      category: 'hero',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'facebook', 'pinterest', 'web'],
      complexity: 4,
      brand_personalities: ['friendly', 'warm', 'playful'],
      industries: ['fitness', 'food_beverage', 'travel'],
      recommended_models: ['nano_banana', 'dalle'],
      estimated_time_seconds: 75,
      cost_tier: 'high',
      requires_approval: true,
      outputs: ['lifestyle_hero', 'square_crop', 'story_crop'],
      tags: ['lifestyle', 'hero', 'contextual'],
    }),
    createMethodMetadata({
      id: 'hero_split_screen',
      name: 'Split Screen Hero',
      description: 'Before/after or comparison split-screen hero',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'display_ads'],
      complexity: 2,
      brand_personalities: ['professional', 'technical'],
      industries: ['technology', 'healthcare', 'b2b'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 45,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['split_hero', 'animated_transition'],
      tags: ['comparison', 'split', 'before_after'],
    }),
    createMethodMetadata({
      id: 'hero_text_overlay',
      name: 'Text Overlay Hero',
      description: 'Hero with integrated typography and messaging',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web', 'email', 'display_ads', 'linkedin'],
      complexity: 3,
      brand_personalities: ['bold', 'professional', 'creative'],
      industries: ['b2b', 'professional_services', 'education'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 50,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['hero_with_text', 'text_variations'],
      tags: ['typography', 'hero', 'messaging'],
    }),
    createMethodMetadata({
      id: 'hero_animated',
      name: 'Animated Hero',
      description: 'Subtle motion hero with parallax or particle effects',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web'],
      motion_support: true,
      complexity: 4,
      brand_personalities: ['creative', 'bold', 'technical'],
      industries: ['technology', 'entertainment', 'fashion'],
      recommended_models: ['veo3', 'runway'],
      estimated_time_seconds: 120,
      cost_tier: 'premium',
      requires_approval: true,
      outputs: ['hero_video', 'hero_lottie', 'fallback_static'],
      tags: ['motion', 'animated', 'interactive'],
    }),
    createMethodMetadata({
      id: 'hero_abstract',
      name: 'Abstract Hero',
      description: 'Abstract, artistic hero for brand campaigns',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web', 'print', 'display_ads'],
      complexity: 3,
      brand_personalities: ['creative', 'bold', 'edgy'],
      industries: ['fashion', 'entertainment', 'technology'],
      recommended_models: ['midjourney', 'nano_banana'],
      estimated_time_seconds: 60,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['abstract_hero', 'pattern_variant'],
      tags: ['abstract', 'artistic', 'conceptual'],
    }),
    createMethodMetadata({
      id: 'hero_seasonal',
      name: 'Seasonal Hero',
      description: 'Holiday or seasonal themed hero visual',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web', 'email', 'facebook', 'instagram'],
      complexity: 3,
      brand_personalities: ['friendly', 'warm', 'playful'],
      industries: ['retail', 'food_beverage', 'travel'],
      recommended_models: ['dalle', 'nano_banana'],
      estimated_time_seconds: 55,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['seasonal_hero', 'social_variants'],
      tags: ['seasonal', 'holiday', 'promotional'],
    }),
    createMethodMetadata({
      id: 'hero_announcement',
      name: 'Announcement Hero',
      description: 'Product launch or news announcement hero',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web', 'email', 'linkedin', 'twitter'],
      complexity: 2,
      brand_personalities: ['professional', 'bold'],
      industries: ['technology', 'b2b', 'professional_services'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 40,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['announcement_hero', 'social_card'],
      tags: ['announcement', 'launch', 'news'],
    }),
    createMethodMetadata({
      id: 'hero_testimonial',
      name: 'Testimonial Hero',
      description: 'Hero featuring customer quote and imagery',
      category: 'hero',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'email'],
      complexity: 2,
      brand_personalities: ['warm', 'professional', 'friendly'],
      industries: ['b2b', 'professional_services', 'healthcare'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 45,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['testimonial_hero', 'quote_card'],
      tags: ['testimonial', 'social_proof', 'quote'],
    }),
  ];

  // Social Sets (12 methods)
  const socialMethods: MethodMetadata[] = [
    createMethodMetadata({
      id: 'social_feed_grid',
      name: 'Feed Grid Set',
      description: 'Cohesive 9-post grid for Instagram feed',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram'],
      complexity: 3,
      brand_personalities: ['creative', 'minimal', 'elegant'],
      industries: ['fashion', 'beauty', 'travel'],
      recommended_models: ['dalle', 'nano_banana'],
      estimated_time_seconds: 90,
      cost_tier: 'high',
      requires_approval: true,
      outputs: ['grid_set_9', 'preview_mockup'],
      tags: ['grid', 'instagram', 'cohesive'],
    }),
    createMethodMetadata({
      id: 'social_story_series',
      name: 'Story Series',
      description: 'Connected story sequence (3-5 frames)',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'facebook', 'snapchat'],
      motion_support: true,
      complexity: 2,
      brand_personalities: ['playful', 'friendly', 'bold'],
      industries: ['retail', 'food_beverage', 'entertainment'],
      recommended_models: ['dalle', 'veo3'],
      estimated_time_seconds: 60,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['story_frames', 'animated_version'],
      tags: ['stories', 'series', 'sequence'],
    }),
    createMethodMetadata({
      id: 'social_reel_cover',
      name: 'Reel Cover Set',
      description: 'Thumbnail covers for video reels',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'tiktok', 'youtube_shorts'],
      complexity: 1,
      brand_personalities: ['bold', 'playful', 'creative'],
      industries: ['entertainment', 'fitness', 'fashion'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 30,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['cover_set', 'text_variations'],
      tags: ['reels', 'covers', 'thumbnails'],
    }),
    createMethodMetadata({
      id: 'social_linkedin_document',
      name: 'LinkedIn Document',
      description: 'PDF carousel document for LinkedIn',
      category: 'social_set',
      primary_channel: 'linkedin',
      supported_channels: ['linkedin'],
      complexity: 3,
      brand_personalities: ['professional', 'technical', 'minimal'],
      industries: ['b2b', 'technology', 'professional_services'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 75,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['document_pdf', 'slide_images'],
      tags: ['linkedin', 'document', 'carousel'],
    }),
    createMethodMetadata({
      id: 'social_quote_cards',
      name: 'Quote Card Set',
      description: 'Shareable quote cards with brand styling',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'twitter', 'linkedin', 'pinterest'],
      complexity: 1,
      brand_personalities: ['professional', 'warm', 'elegant'],
      industries: ['education', 'professional_services', 'nonprofit'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 25,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['quote_cards_5', 'story_variants'],
      tags: ['quotes', 'shareable', 'cards'],
    }),
    createMethodMetadata({
      id: 'social_poll_graphics',
      name: 'Poll Graphics',
      description: 'Engaging poll and question graphics',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'twitter', 'linkedin'],
      complexity: 1,
      brand_personalities: ['playful', 'friendly'],
      industries: ['retail', 'entertainment', 'food_beverage'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 20,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['poll_graphics', 'results_template'],
      tags: ['polls', 'engagement', 'interactive'],
    }),
    createMethodMetadata({
      id: 'social_announcement_pack',
      name: 'Announcement Pack',
      description: 'Multi-platform announcement graphics',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'facebook', 'twitter', 'linkedin'],
      complexity: 2,
      brand_personalities: ['professional', 'bold'],
      industries: ['technology', 'b2b', 'retail'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 45,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['announcement_set', 'story_versions'],
      tags: ['announcement', 'multi_platform'],
    }),
    createMethodMetadata({
      id: 'social_countdown',
      name: 'Countdown Series',
      description: 'Launch countdown graphics series',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'twitter', 'facebook'],
      motion_support: true,
      complexity: 2,
      brand_personalities: ['bold', 'playful', 'creative'],
      industries: ['entertainment', 'technology', 'retail'],
      recommended_models: ['dalle', 'veo3'],
      estimated_time_seconds: 50,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['countdown_set', 'animated_numbers'],
      tags: ['countdown', 'launch', 'teaser'],
    }),
    createMethodMetadata({
      id: 'social_thread_visuals',
      name: 'Thread Visuals',
      description: 'Connected visuals for Twitter/X threads',
      category: 'social_set',
      primary_channel: 'twitter',
      supported_channels: ['twitter', 'threads'],
      complexity: 2,
      brand_personalities: ['professional', 'technical', 'creative'],
      industries: ['technology', 'education', 'b2b'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 40,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['thread_images', 'header_image'],
      tags: ['threads', 'twitter', 'series'],
    }),
    createMethodMetadata({
      id: 'social_pinterest_pins',
      name: 'Pinterest Pin Set',
      description: 'Vertical pins optimized for Pinterest',
      category: 'social_set',
      primary_channel: 'pinterest',
      supported_channels: ['pinterest'],
      complexity: 2,
      brand_personalities: ['elegant', 'creative', 'warm'],
      industries: ['fashion', 'food_beverage', 'travel', 'beauty'],
      recommended_models: ['dalle', 'nano_banana'],
      estimated_time_seconds: 45,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['pin_set', 'idea_pins'],
      tags: ['pinterest', 'vertical', 'pins'],
    }),
    createMethodMetadata({
      id: 'social_ugc_frame',
      name: 'UGC Frame Template',
      description: 'Branded frames for user-generated content',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'tiktok', 'facebook'],
      complexity: 1,
      brand_personalities: ['playful', 'friendly'],
      industries: ['retail', 'food_beverage', 'entertainment'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 25,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['frame_templates', 'usage_guide'],
      tags: ['ugc', 'frames', 'templates'],
    }),
    createMethodMetadata({
      id: 'social_highlight_covers',
      name: 'Highlight Covers',
      description: 'Instagram story highlight cover icons',
      category: 'social_set',
      primary_channel: 'instagram',
      supported_channels: ['instagram'],
      complexity: 1,
      brand_personalities: ['minimal', 'elegant', 'professional'],
      industries: ['fashion', 'beauty', 'professional_services'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 30,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['cover_icons_10', 'custom_icons'],
      tags: ['highlights', 'icons', 'instagram'],
    }),
  ];

  // Thumbnails (8 methods)
  const thumbnailMethods: MethodMetadata[] = [
    createMethodMetadata({
      id: 'thumb_youtube',
      name: 'YouTube Thumbnail',
      description: 'High-CTR YouTube video thumbnail',
      category: 'thumbnail',
      primary_channel: 'youtube',
      supported_channels: ['youtube'],
      complexity: 2,
      brand_personalities: ['bold', 'playful', 'professional'],
      industries: ['entertainment', 'education', 'technology'],
      recommended_models: ['dalle', 'nano_banana'],
      estimated_time_seconds: 35,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['thumbnail', 'text_variations'],
      tags: ['youtube', 'thumbnail', 'ctr'],
    }),
    createMethodMetadata({
      id: 'thumb_podcast',
      name: 'Podcast Episode Art',
      description: 'Episode-specific podcast artwork',
      category: 'thumbnail',
      primary_channel: 'podcast',
      supported_channels: ['podcast', 'youtube'],
      complexity: 2,
      brand_personalities: ['professional', 'creative', 'warm'],
      industries: ['entertainment', 'education', 'b2b'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 30,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['episode_art', 'social_promo'],
      tags: ['podcast', 'episode', 'audio'],
    }),
    createMethodMetadata({
      id: 'thumb_blog',
      name: 'Blog Featured Image',
      description: 'Featured image for blog articles',
      category: 'thumbnail',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'twitter'],
      complexity: 1,
      brand_personalities: ['professional', 'minimal', 'creative'],
      industries: ['b2b', 'technology', 'education'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 25,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['featured_image', 'social_card'],
      tags: ['blog', 'featured', 'article'],
    }),
    createMethodMetadata({
      id: 'thumb_course',
      name: 'Course Thumbnail',
      description: 'Online course or lesson thumbnail',
      category: 'thumbnail',
      primary_channel: 'web',
      supported_channels: ['web', 'youtube'],
      complexity: 2,
      brand_personalities: ['professional', 'technical', 'friendly'],
      industries: ['education', 'technology', 'professional_services'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 30,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['course_thumb', 'lesson_thumbs'],
      tags: ['course', 'education', 'learning'],
    }),
    createMethodMetadata({
      id: 'thumb_webinar',
      name: 'Webinar Thumbnail',
      description: 'Webinar registration and replay thumbnail',
      category: 'thumbnail',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'email'],
      complexity: 2,
      brand_personalities: ['professional', 'technical'],
      industries: ['b2b', 'technology', 'education'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 30,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['webinar_thumb', 'social_promo'],
      tags: ['webinar', 'event', 'registration'],
    }),
    createMethodMetadata({
      id: 'thumb_product',
      name: 'Product Listing Thumb',
      description: 'E-commerce product listing thumbnail',
      category: 'thumbnail',
      primary_channel: 'web',
      supported_channels: ['web', 'pinterest', 'google_business'],
      complexity: 1,
      brand_personalities: ['minimal', 'professional', 'elegant'],
      industries: ['retail', 'fashion', 'beauty'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 20,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['product_thumb', 'gallery_images'],
      tags: ['product', 'ecommerce', 'listing'],
    }),
    createMethodMetadata({
      id: 'thumb_event',
      name: 'Event Thumbnail',
      description: 'Event promotion thumbnail',
      category: 'thumbnail',
      primary_channel: 'web',
      supported_channels: ['web', 'facebook', 'linkedin'],
      complexity: 2,
      brand_personalities: ['bold', 'professional', 'creative'],
      industries: ['entertainment', 'education', 'b2b'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 30,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['event_thumb', 'social_cards'],
      tags: ['event', 'promotion', 'registration'],
    }),
    createMethodMetadata({
      id: 'thumb_newsletter',
      name: 'Newsletter Thumbnail',
      description: 'Newsletter issue preview thumbnail',
      category: 'thumbnail',
      primary_channel: 'email',
      supported_channels: ['email', 'web'],
      complexity: 1,
      brand_personalities: ['professional', 'minimal', 'warm'],
      industries: ['b2b', 'professional_services', 'education'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 20,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['newsletter_thumb', 'header_image'],
      tags: ['newsletter', 'email', 'preview'],
    }),
  ];

  // Carousels (8 methods)
  const carouselMethods: MethodMetadata[] = [
    createMethodMetadata({
      id: 'carousel_educational',
      name: 'Educational Carousel',
      description: 'Step-by-step educational content carousel',
      category: 'carousel',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'linkedin'],
      complexity: 3,
      brand_personalities: ['professional', 'technical', 'friendly'],
      industries: ['education', 'technology', 'healthcare'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 60,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['carousel_slides_10', 'cover_slide'],
      tags: ['educational', 'tutorial', 'steps'],
    }),
    createMethodMetadata({
      id: 'carousel_product_showcase',
      name: 'Product Showcase Carousel',
      description: 'Multi-product or multi-feature carousel',
      category: 'carousel',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'facebook'],
      complexity: 2,
      brand_personalities: ['elegant', 'minimal', 'professional'],
      industries: ['retail', 'technology', 'beauty'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 50,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['product_carousel', 'feature_callouts'],
      tags: ['product', 'showcase', 'features'],
    }),
    createMethodMetadata({
      id: 'carousel_story_narrative',
      name: 'Story Narrative Carousel',
      description: 'Brand story told through carousel slides',
      category: 'carousel',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'linkedin'],
      complexity: 4,
      brand_personalities: ['warm', 'creative', 'elegant'],
      industries: ['nonprofit', 'fashion', 'food_beverage'],
      recommended_models: ['dalle', 'nano_banana'],
      estimated_time_seconds: 75,
      cost_tier: 'high',
      requires_approval: true,
      outputs: ['narrative_carousel', 'motion_version'],
      tags: ['story', 'narrative', 'brand'],
    }),
    createMethodMetadata({
      id: 'carousel_comparison',
      name: 'Comparison Carousel',
      description: 'Side-by-side comparison carousel',
      category: 'carousel',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'linkedin', 'twitter'],
      complexity: 2,
      brand_personalities: ['professional', 'technical'],
      industries: ['technology', 'b2b', 'healthcare'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 45,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['comparison_slides', 'summary_slide'],
      tags: ['comparison', 'versus', 'analysis'],
    }),
    createMethodMetadata({
      id: 'carousel_tips',
      name: 'Tips & Tricks Carousel',
      description: 'Quick tips carousel format',
      category: 'carousel',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'linkedin', 'pinterest'],
      complexity: 2,
      brand_personalities: ['friendly', 'professional', 'playful'],
      industries: ['education', 'fitness', 'food_beverage'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 40,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['tips_carousel', 'save_worthy_slides'],
      tags: ['tips', 'tricks', 'advice'],
    }),
    createMethodMetadata({
      id: 'carousel_testimonial',
      name: 'Testimonial Carousel',
      description: 'Customer testimonials carousel',
      category: 'carousel',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'facebook', 'linkedin'],
      complexity: 2,
      brand_personalities: ['warm', 'professional', 'friendly'],
      industries: ['b2b', 'professional_services', 'healthcare'],
      recommended_models: ['dalle', 'gemini'],
      estimated_time_seconds: 40,
      cost_tier: 'medium',
      requires_approval: true,
      outputs: ['testimonial_slides', 'photo_variants'],
      tags: ['testimonial', 'reviews', 'social_proof'],
    }),
    createMethodMetadata({
      id: 'carousel_process',
      name: 'Process Flow Carousel',
      description: 'Step-by-step process visualization',
      category: 'carousel',
      primary_channel: 'linkedin',
      supported_channels: ['linkedin', 'instagram'],
      complexity: 3,
      brand_personalities: ['professional', 'technical', 'minimal'],
      industries: ['b2b', 'technology', 'professional_services'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 55,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['process_slides', 'flow_diagram'],
      tags: ['process', 'workflow', 'steps'],
    }),
    createMethodMetadata({
      id: 'carousel_portfolio',
      name: 'Portfolio Carousel',
      description: 'Work samples portfolio carousel',
      category: 'carousel',
      primary_channel: 'instagram',
      supported_channels: ['instagram', 'linkedin'],
      complexity: 2,
      brand_personalities: ['creative', 'professional', 'elegant'],
      industries: ['fashion', 'entertainment', 'professional_services'],
      recommended_models: ['dalle', 'nano_banana'],
      estimated_time_seconds: 45,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['portfolio_slides', 'cover_slide'],
      tags: ['portfolio', 'showcase', 'work'],
    }),
  ];

  // Data Viz (8 methods)
  const dataVizMethods: MethodMetadata[] = [
    createMethodMetadata({
      id: 'dataviz_bar_chart',
      name: 'Branded Bar Chart',
      description: 'Bar chart with brand styling',
      category: 'data_viz',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'email'],
      complexity: 2,
      brand_personalities: ['professional', 'technical', 'minimal'],
      industries: ['finance', 'b2b', 'technology'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 30,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['bar_chart', 'animated_version'],
      tags: ['chart', 'data', 'visualization'],
    }),
    createMethodMetadata({
      id: 'dataviz_pie_chart',
      name: 'Branded Pie Chart',
      description: 'Pie/donut chart with brand colors',
      category: 'data_viz',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'email'],
      complexity: 2,
      brand_personalities: ['professional', 'minimal'],
      industries: ['finance', 'b2b', 'technology'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 25,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['pie_chart', 'percentage_labels'],
      tags: ['pie', 'donut', 'percentage'],
    }),
    createMethodMetadata({
      id: 'dataviz_line_graph',
      name: 'Trend Line Graph',
      description: 'Line graph for trends over time',
      category: 'data_viz',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'email'],
      motion_support: true,
      complexity: 3,
      brand_personalities: ['professional', 'technical'],
      industries: ['finance', 'technology', 'b2b'],
      recommended_models: ['gemini', 'veo3'],
      estimated_time_seconds: 35,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['line_graph', 'animated_draw'],
      tags: ['trend', 'time_series', 'growth'],
    }),
    createMethodMetadata({
      id: 'dataviz_stats_cards',
      name: 'Stats Cards',
      description: 'Key metrics in card format',
      category: 'data_viz',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'instagram'],
      motion_support: true,
      complexity: 2,
      brand_personalities: ['professional', 'bold', 'minimal'],
      industries: ['b2b', 'technology', 'finance'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 25,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['stats_cards', 'animated_counters'],
      tags: ['stats', 'metrics', 'kpi'],
    }),
    createMethodMetadata({
      id: 'dataviz_comparison_table',
      name: 'Comparison Table',
      description: 'Visual comparison table',
      category: 'data_viz',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin'],
      complexity: 2,
      brand_personalities: ['professional', 'technical', 'minimal'],
      industries: ['technology', 'b2b', 'finance'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 35,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['comparison_table', 'highlight_variants'],
      tags: ['table', 'comparison', 'features'],
    }),
    createMethodMetadata({
      id: 'dataviz_timeline',
      name: 'Timeline Visualization',
      description: 'Historical or project timeline',
      category: 'data_viz',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'instagram'],
      complexity: 3,
      brand_personalities: ['professional', 'elegant', 'creative'],
      industries: ['education', 'nonprofit', 'b2b'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 45,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['timeline', 'milestone_cards'],
      tags: ['timeline', 'history', 'milestones'],
    }),
    createMethodMetadata({
      id: 'dataviz_map',
      name: 'Data Map',
      description: 'Geographic data visualization',
      category: 'data_viz',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin'],
      complexity: 3,
      brand_personalities: ['professional', 'technical'],
      industries: ['real_estate', 'travel', 'b2b'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 50,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['data_map', 'regional_callouts'],
      tags: ['map', 'geographic', 'regional'],
    }),
    createMethodMetadata({
      id: 'dataviz_gauge',
      name: 'Progress Gauge',
      description: 'Gauge or progress indicator',
      category: 'data_viz',
      primary_channel: 'web',
      supported_channels: ['web', 'email'],
      motion_support: true,
      complexity: 2,
      brand_personalities: ['technical', 'professional', 'bold'],
      industries: ['technology', 'finance', 'fitness'],
      recommended_models: ['gemini', 'veo3'],
      estimated_time_seconds: 25,
      cost_tier: 'low',
      requires_approval: false,
      outputs: ['gauge', 'animated_fill'],
      tags: ['gauge', 'progress', 'metric'],
    }),
  ];

  // Animation & Motion (10 methods)
  const animationMethods: MethodMetadata[] = [
    createMethodMetadata({
      id: 'anim_logo_reveal',
      name: 'Logo Reveal Animation',
      description: 'Animated logo intro sequence',
      category: 'animation',
      primary_channel: 'web',
      supported_channels: ['web', 'youtube'],
      motion_support: true,
      complexity: 3,
      brand_personalities: ['professional', 'bold', 'elegant'],
      industries: ['technology', 'entertainment', 'fashion'],
      recommended_models: ['veo3', 'runway'],
      estimated_time_seconds: 60,
      cost_tier: 'high',
      requires_approval: true,
      outputs: ['logo_animation', 'lottie_file', 'gif'],
      tags: ['logo', 'reveal', 'intro'],
    }),
    createMethodMetadata({
      id: 'anim_loading_spinner',
      name: 'Loading Spinner',
      description: 'Branded loading animation',
      category: 'animation',
      primary_channel: 'web',
      supported_channels: ['web'],
      motion_support: true,
      complexity: 2,
      brand_personalities: ['minimal', 'professional', 'playful'],
      industries: ['technology', 'retail', 'b2b'],
      recommended_models: ['veo3', 'gemini'],
      estimated_time_seconds: 30,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['spinner_lottie', 'spinner_gif'],
      tags: ['loading', 'spinner', 'ui'],
    }),
    createMethodMetadata({
      id: 'anim_icon_set',
      name: 'Animated Icon Set',
      description: 'Icons with hover/click animations',
      category: 'animation',
      primary_channel: 'web',
      supported_channels: ['web'],
      motion_support: true,
      complexity: 3,
      brand_personalities: ['playful', 'friendly', 'creative'],
      industries: ['technology', 'entertainment', 'retail'],
      recommended_models: ['veo3', 'gemini'],
      estimated_time_seconds: 60,
      cost_tier: 'high',
      requires_approval: false,
      outputs: ['animated_icons', 'lottie_set'],
      tags: ['icons', 'animated', 'microinteractions'],
    }),
    createMethodMetadata({
      id: 'anim_text_kinetic',
      name: 'Kinetic Typography',
      description: 'Text-based animation sequence',
      category: 'animation',
      primary_channel: 'youtube',
      supported_channels: ['youtube', 'instagram', 'tiktok'],
      motion_support: true,
      complexity: 4,
      brand_personalities: ['bold', 'creative', 'edgy'],
      industries: ['entertainment', 'fashion', 'technology'],
      recommended_models: ['veo3', 'runway'],
      estimated_time_seconds: 90,
      cost_tier: 'premium',
      requires_approval: true,
      outputs: ['kinetic_video', 'timing_markers'],
      tags: ['typography', 'kinetic', 'text'],
    }),
    createMethodMetadata({
      id: 'anim_particle_effect',
      name: 'Particle Effect',
      description: 'Particle system animation',
      category: 'animation',
      primary_channel: 'web',
      supported_channels: ['web', 'youtube'],
      motion_support: true,
      complexity: 4,
      brand_personalities: ['creative', 'technical', 'bold'],
      industries: ['technology', 'entertainment', 'fashion'],
      recommended_models: ['veo3', 'runway'],
      estimated_time_seconds: 75,
      cost_tier: 'high',
      requires_approval: false,
      outputs: ['particle_video', 'loop_version'],
      tags: ['particles', 'effect', 'abstract'],
    }),
    createMethodMetadata({
      id: 'anim_transition_pack',
      name: 'Transition Pack',
      description: 'Branded video transitions',
      category: 'animation',
      primary_channel: 'youtube',
      supported_channels: ['youtube', 'tiktok'],
      motion_support: true,
      complexity: 3,
      brand_personalities: ['bold', 'creative', 'professional'],
      industries: ['entertainment', 'technology', 'fashion'],
      recommended_models: ['veo3', 'runway'],
      estimated_time_seconds: 60,
      cost_tier: 'high',
      requires_approval: false,
      outputs: ['transitions_10', 'usage_guide'],
      tags: ['transitions', 'video', 'editing'],
    }),
    createMethodMetadata({
      id: 'anim_button_states',
      name: 'Button State Animations',
      description: 'Button hover, click, and loading states',
      category: 'animation',
      primary_channel: 'web',
      supported_channels: ['web'],
      motion_support: true,
      complexity: 2,
      brand_personalities: ['professional', 'minimal', 'playful'],
      industries: ['technology', 'retail', 'b2b'],
      recommended_models: ['veo3', 'gemini'],
      estimated_time_seconds: 35,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['button_lottie', 'css_animations'],
      tags: ['button', 'states', 'ui'],
    }),
    createMethodMetadata({
      id: 'anim_scroll_reveal',
      name: 'Scroll Reveal Animation',
      description: 'Page element reveal animations',
      category: 'animation',
      primary_channel: 'web',
      supported_channels: ['web'],
      motion_support: true,
      complexity: 3,
      brand_personalities: ['professional', 'elegant', 'creative'],
      industries: ['technology', 'professional_services', 'fashion'],
      recommended_models: ['veo3', 'gemini'],
      estimated_time_seconds: 45,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['reveal_animations', 'timing_presets'],
      tags: ['scroll', 'reveal', 'website'],
    }),
    createMethodMetadata({
      id: 'anim_countdown_timer',
      name: 'Countdown Timer Animation',
      description: 'Animated countdown for launches',
      category: 'animation',
      primary_channel: 'web',
      supported_channels: ['web', 'instagram'],
      motion_support: true,
      complexity: 2,
      brand_personalities: ['bold', 'playful', 'professional'],
      industries: ['retail', 'entertainment', 'technology'],
      recommended_models: ['veo3', 'gemini'],
      estimated_time_seconds: 40,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['countdown_lottie', 'number_animations'],
      tags: ['countdown', 'timer', 'launch'],
    }),
    createMethodMetadata({
      id: 'anim_character',
      name: 'Character Animation',
      description: 'Simple character or mascot animation',
      category: 'animation',
      primary_channel: 'web',
      supported_channels: ['web', 'instagram', 'youtube'],
      motion_support: true,
      complexity: 5,
      brand_personalities: ['playful', 'friendly', 'creative'],
      industries: ['entertainment', 'education', 'food_beverage'],
      recommended_models: ['veo3', 'runway'],
      estimated_time_seconds: 120,
      cost_tier: 'premium',
      requires_approval: true,
      outputs: ['character_animation', 'expressions_set'],
      tags: ['character', 'mascot', 'animated'],
    }),
  ];

  // Infographics (6 methods)
  const infographicMethods: MethodMetadata[] = [
    createMethodMetadata({
      id: 'infographic_vertical',
      name: 'Vertical Infographic',
      description: 'Long-form scrollable infographic',
      category: 'infographic',
      primary_channel: 'pinterest',
      supported_channels: ['pinterest', 'web'],
      complexity: 4,
      brand_personalities: ['professional', 'technical', 'creative'],
      industries: ['b2b', 'education', 'healthcare'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 90,
      cost_tier: 'high',
      requires_approval: true,
      outputs: ['infographic', 'section_images'],
      tags: ['infographic', 'vertical', 'data'],
    }),
    createMethodMetadata({
      id: 'infographic_comparison',
      name: 'Comparison Infographic',
      description: 'Side-by-side comparison visual',
      category: 'infographic',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'pinterest'],
      complexity: 3,
      brand_personalities: ['professional', 'technical'],
      industries: ['technology', 'b2b', 'healthcare'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 60,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['comparison_infographic', 'social_cards'],
      tags: ['comparison', 'versus', 'infographic'],
    }),
    createMethodMetadata({
      id: 'infographic_process',
      name: 'Process Infographic',
      description: 'Step-by-step process visualization',
      category: 'infographic',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin'],
      complexity: 3,
      brand_personalities: ['professional', 'technical', 'minimal'],
      industries: ['b2b', 'technology', 'professional_services'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 60,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['process_infographic', 'step_cards'],
      tags: ['process', 'workflow', 'steps'],
    }),
    createMethodMetadata({
      id: 'infographic_stats',
      name: 'Statistics Infographic',
      description: 'Data and statistics visualization',
      category: 'infographic',
      primary_channel: 'linkedin',
      supported_channels: ['linkedin', 'web', 'email'],
      complexity: 3,
      brand_personalities: ['professional', 'technical'],
      industries: ['finance', 'b2b', 'healthcare'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 55,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['stats_infographic', 'highlight_cards'],
      tags: ['statistics', 'data', 'numbers'],
    }),
    createMethodMetadata({
      id: 'infographic_timeline',
      name: 'Timeline Infographic',
      description: 'Historical or project timeline',
      category: 'infographic',
      primary_channel: 'web',
      supported_channels: ['web', 'linkedin', 'pinterest'],
      complexity: 4,
      brand_personalities: ['professional', 'elegant', 'creative'],
      industries: ['education', 'nonprofit', 'b2b'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 75,
      cost_tier: 'high',
      requires_approval: false,
      outputs: ['timeline_infographic', 'milestone_cards'],
      tags: ['timeline', 'history', 'milestones'],
    }),
    createMethodMetadata({
      id: 'infographic_resume',
      name: 'Visual Resume',
      description: 'Infographic-style resume/CV',
      category: 'infographic',
      primary_channel: 'linkedin',
      supported_channels: ['linkedin', 'web'],
      complexity: 3,
      brand_personalities: ['professional', 'creative', 'minimal'],
      industries: ['professional_services', 'technology', 'fashion'],
      recommended_models: ['gemini', 'dalle'],
      estimated_time_seconds: 60,
      cost_tier: 'medium',
      requires_approval: false,
      outputs: ['visual_resume', 'linkedin_version'],
      tags: ['resume', 'cv', 'personal'],
    }),
  ];

  // Register all methods
  const allMethods = [
    ...heroMethods,
    ...socialMethods,
    ...thumbnailMethods,
    ...carouselMethods,
    ...dataVizMethods,
    ...animationMethods,
    ...infographicMethods,
  ];

  for (const method of allMethods) {
    registerMethod(method);
  }
}

// Export method count
export function getMethodCount(): number {
  return 62; // Additional methods from this catalog
}

export default initializeMethodCatalog;
