-- Guardian Phase H01: AI-Assisted Rule Authoring
-- Migration: 551
-- Purpose: Telemetry for AI-assisted rule suggestions (privacy-friendly)
-- Tables: guardian_ai_rule_suggestions

-- ============================================================================
-- TABLE: guardian_ai_rule_suggestions
-- ============================================================================
-- Tracks AI-assisted rule authoring usage without storing prompts/responses
-- Lightweight telemetry for monitoring AI feature adoption and performance
-- No sensitive data stored (privacy-friendly)
-- ============================================================================

CREATE TABLE IF NOT EXISTS guardian_ai_rule_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  user_id UUID,
  rule_id UUID REFERENCES guardian_alert_rules(id) ON DELETE SET NULL,
  action TEXT NOT NULL CHECK (action IN ('suggest', 'refine', 'validate')),
  model TEXT NOT NULL,
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  latency_ms INTEGER,
  status TEXT NOT NULL CHECK (status IN ('success', 'error', 'timeout')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- INDEXES
-- ============================================================================
CREATE INDEX idx_guardian_ai_rule_suggestions_tenant
  ON guardian_ai_rule_suggestions (tenant_id, created_at DESC);

CREATE INDEX idx_guardian_ai_rule_suggestions_rule
  ON guardian_ai_rule_suggestions (rule_id);

CREATE INDEX idx_guardian_ai_rule_suggestions_status
  ON guardian_ai_rule_suggestions (tenant_id, status);

-- ============================================================================
-- RLS (Row Level Security)
-- ============================================================================
ALTER TABLE guardian_ai_rule_suggestions ENABLE ROW LEVEL SECURITY;

-- Tenants can view their own AI usage logs
CREATE POLICY tenant_rw_guardian_ai_rule_suggestions
  ON guardian_ai_rule_suggestions
  FOR ALL
  USING (tenant_id = auth.uid())
  WITH CHECK (tenant_id = auth.uid());

-- Service role: Full access
CREATE POLICY service_all_guardian_ai_rule_suggestions
  ON guardian_ai_rule_suggestions
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- COMMENTS
-- ============================================================================
COMMENT ON TABLE guardian_ai_rule_suggestions IS 'Telemetry for AI-assisted rule authoring (no prompts/responses stored)';
COMMENT ON COLUMN guardian_ai_rule_suggestions.action IS 'AI action: suggest (new rule), refine (improve existing), validate (check rule)';
COMMENT ON COLUMN guardian_ai_rule_suggestions.status IS 'Request outcome: success, error, or timeout';
COMMENT ON COLUMN guardian_ai_rule_suggestions.prompt_tokens IS 'Input tokens sent to AI model';
COMMENT ON COLUMN guardian_ai_rule_suggestions.completion_tokens IS 'Output tokens generated by AI model';
COMMENT ON COLUMN guardian_ai_rule_suggestions.latency_ms IS 'Time taken for AI response (milliseconds)';
