import type { GalleryTemplate } from "@/types/template-gallery"

export const templateGalleryData: GalleryTemplate[] = [
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    description: "Professional template with a clean blue color scheme, perfect for business reports and proposals.",
    thumbnailUrl: "/placeholder.svg?key=87fhi",
    previewUrl: "/blue-document-template.png",
    category: ["business", "classic", "featured"],
    tags: ["professional", "corporate", "clean", "business"],
    popularity: 98,
    author: "Streamline Design",
    isPremium: false,
    createdAt: "2023-01-15T00:00:00Z",
    updatedAt: "2023-01-15T00:00:00Z",
    isDefault: false,
    primaryColor: "#1e3a8a",
    secondaryColor: "#60a5fa",
    accentColor: "#f59e0b",
    fontFamily: "helvetica",
    headerTitle: "Architecture Blueprint",
    footerText: "Confidential & Proprietary",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "classic",
    companyName: "Streamline Solutions",
    contactInfo: "contact@example.com\n(123) 456-7890",
  },
  {
    id: "modern-dark",
    name: "Modern Dark",
    description: "Sleek dark-themed template with vibrant accents for a contemporary and sophisticated look.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=modern%20dark%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=modern%20dark%20document%20template%20preview",
    category: ["modern", "creative", "featured"],
    tags: ["dark", "sleek", "modern", "vibrant"],
    popularity: 92,
    author: "Design Labs",
    authorUrl: "https://example.com",
    isPremium: true,
    createdAt: "2023-02-20T00:00:00Z",
    updatedAt: "2023-02-20T00:00:00Z",
    isDefault: false,
    primaryColor: "#18181b",
    secondaryColor: "#3b82f6",
    accentColor: "#ec4899",
    fontFamily: "arial",
    headerTitle: "Project Blueprint",
    footerText: "Confidential",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "modern",
    companyName: "Design Labs Inc.",
    contactInfo: "hello@designlabs.example\n(800) 555-1234",
    watermark: "CONFIDENTIAL",
  },
  {
    id: "tech-blueprint",
    name: "Tech Blueprint",
    description: "Technical template designed specifically for architecture blueprints with detailed specifications.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=technical%20blueprint%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=technical%20blueprint%20document%20template%20preview",
    category: ["technical", "business"],
    tags: ["technical", "blueprint", "architecture", "engineering"],
    popularity: 87,
    author: "TechDocs",
    isPremium: false,
    createdAt: "2023-03-10T00:00:00Z",
    updatedAt: "2023-03-10T00:00:00Z",
    isDefault: false,
    primaryColor: "#0f172a",
    secondaryColor: "#0ea5e9",
    accentColor: "#22c55e",
    fontFamily: "courier",
    headerTitle: "Technical Blueprint",
    footerText: "Technical Documentation",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "technical",
    companyName: "TechDocs Solutions",
    contactInfo: "support@techdocs.example\n(555) 123-4567",
  },
  {
    id: "minimalist",
    name: "Minimalist",
    description: "Clean, minimal design with ample white space for a modern and uncluttered presentation.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=minimalist%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=minimalist%20document%20template%20preview",
    category: ["minimal", "modern"],
    tags: ["minimal", "clean", "simple", "elegant"],
    popularity: 85,
    author: "Minimalist Design Co.",
    isPremium: false,
    createdAt: "2023-04-05T00:00:00Z",
    updatedAt: "2023-04-05T00:00:00Z",
    isDefault: false,
    primaryColor: "#262626",
    secondaryColor: "#737373",
    accentColor: "#ef4444",
    fontFamily: "helvetica",
    headerTitle: "",
    footerText: "",
    includeTimestamp: false,
    includePageNumbers: true,
    includeCoverPage: false,
    templateStyle: "minimal",
    companyName: "",
    contactInfo: "",
  },
  {
    id: "bold-impact",
    name: "Bold Impact",
    description: "High-contrast template with bold colors and typography for maximum visual impact.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=bold%20impact%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=bold%20impact%20document%20template%20preview",
    category: ["bold", "creative", "featured"],
    tags: ["bold", "vibrant", "impactful", "colorful"],
    popularity: 79,
    author: "Bold Design Studio",
    isPremium: true,
    createdAt: "2023-05-12T00:00:00Z",
    updatedAt: "2023-05-12T00:00:00Z",
    isDefault: false,
    primaryColor: "#000000",
    secondaryColor: "#f97316",
    accentColor: "#8b5cf6",
    fontFamily: "arial",
    headerTitle: "ARCHITECTURE BLUEPRINT",
    footerText: "CONFIDENTIAL DOCUMENT",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "bold",
    companyName: "Bold Designs",
    contactInfo: "info@bolddesigns.example\n(888) 555-BOLD",
    watermark: "",
  },
  {
    id: "eco-green",
    name: "Eco Green",
    description: "Nature-inspired template with green accents, perfect for environmentally conscious projects.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=eco%20green%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=eco%20green%20document%20template%20preview",
    category: ["business", "creative"],
    tags: ["eco", "green", "sustainable", "natural"],
    popularity: 76,
    author: "Green Design",
    isPremium: false,
    createdAt: "2023-06-18T00:00:00Z",
    updatedAt: "2023-06-18T00:00:00Z",
    isDefault: false,
    primaryColor: "#14532d",
    secondaryColor: "#84cc16",
    accentColor: "#0ea5e9",
    fontFamily: "times",
    headerTitle: "Sustainable Blueprint",
    footerText: "Printed on recycled paper",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "classic",
    companyName: "EcoSolutions",
    contactInfo: "green@ecosolutions.example\n(555) ECO-FRIENDLY",
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    description: "Elegant template with gold accents for high-end projects and premium presentations.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=luxury%20gold%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=luxury%20gold%20document%20template%20preview",
    category: ["creative", "bold"],
    tags: ["luxury", "elegant", "premium", "gold"],
    popularity: 82,
    author: "Luxury Designs",
    isPremium: true,
    createdAt: "2023-07-22T00:00:00Z",
    updatedAt: "2023-07-22T00:00:00Z",
    isDefault: false,
    primaryColor: "#1c1917",
    secondaryColor: "#ca8a04",
    accentColor: "#f5f5f4",
    fontFamily: "times",
    headerTitle: "Premium Architecture Blueprint",
    footerText: "Exclusive & Confidential",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "bold",
    companyName: "Luxury Architects",
    contactInfo: "contact@luxuryarchitects.example\n(800) LUXURY",
    watermark: "PREMIUM",
  },
  {
    id: "tech-grid",
    name: "Tech Grid",
    description: "Modern template with a grid-based layout inspired by technology and digital interfaces.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=tech%20grid%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=tech%20grid%20document%20template%20preview",
    category: ["technical", "modern"],
    tags: ["tech", "grid", "digital", "futuristic"],
    popularity: 78,
    author: "Digital Solutions",
    isPremium: false,
    createdAt: "2023-08-15T00:00:00Z",
    updatedAt: "2023-08-15T00:00:00Z",
    isDefault: false,
    primaryColor: "#0f172a",
    secondaryColor: "#06b6d4",
    accentColor: "#a855f7",
    fontFamily: "courier",
    headerTitle: "Digital Blueprint",
    footerText: "Digital Documentation",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "modern",
    companyName: "Digital Solutions Inc.",
    contactInfo: "help@digitalsolutions.example\n(555) DIGITAL",
  },
  {
    id: "classic-serif",
    name: "Classic Serif",
    description: "Traditional template with serif fonts and classic styling for timeless documentation.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=classic%20serif%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=classic%20serif%20document%20template%20preview",
    category: ["classic", "business"],
    tags: ["classic", "traditional", "serif", "timeless"],
    popularity: 72,
    author: "Classic Design",
    isPremium: false,
    createdAt: "2023-09-05T00:00:00Z",
    updatedAt: "2023-09-05T00:00:00Z",
    isDefault: false,
    primaryColor: "#44403c",
    secondaryColor: "#78716c",
    accentColor: "#b91c1c",
    fontFamily: "times",
    headerTitle: "Architecture Documentation",
    footerText: "Proprietary & Confidential",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "classic",
    companyName: "Classic Architects",
    contactInfo: "info@classicarchitects.example\n(555) 123-4567",
  },
  {
    id: "vibrant-creative",
    name: "Vibrant Creative",
    description: "Colorful template with vibrant accents for creative projects and innovative presentations.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=vibrant%20creative%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=vibrant%20creative%20document%20template%20preview",
    category: ["creative", "bold", "featured"],
    tags: ["vibrant", "creative", "colorful", "innovative"],
    popularity: 88,
    author: "Creative Studio",
    isPremium: true,
    createdAt: "2023-10-10T00:00:00Z",
    updatedAt: "2023-10-10T00:00:00Z",
    isDefault: false,
    primaryColor: "#581c87",
    secondaryColor: "#d946ef",
    accentColor: "#fbbf24",
    fontFamily: "helvetica",
    headerTitle: "Creative Blueprint",
    footerText: "Inspired Design",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "modern",
    companyName: "Creative Solutions",
    contactInfo: "hello@creativesolutions.example\n(555) CREATE",
  },
  {
    id: "medical-clean",
    name: "Medical Clean",
    description: "Clean and professional template designed for medical and healthcare documentation.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=medical%20clean%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=medical%20clean%20document%20template%20preview",
    category: ["business", "minimal"],
    tags: ["medical", "healthcare", "clean", "professional"],
    popularity: 74,
    author: "MedDocs",
    isPremium: false,
    createdAt: "2023-11-15T00:00:00Z",
    updatedAt: "2023-11-15T00:00:00Z",
    isDefault: false,
    primaryColor: "#0f766e",
    secondaryColor: "#14b8a6",
    accentColor: "#ef4444",
    fontFamily: "helvetica",
    headerTitle: "Medical Documentation",
    footerText: "Confidential Patient Information",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "minimal",
    companyName: "MedDocs Solutions",
    contactInfo: "info@meddocs.example\n(555) MED-DOCS",
  },
  {
    id: "construction-blueprint",
    name: "Construction Blueprint",
    description: "Specialized template for construction projects with technical details and specifications.",
    thumbnailUrl: "/placeholder.svg?height=300&width=400&query=construction%20blueprint%20document%20template",
    previewUrl: "/placeholder.svg?height=800&width=600&query=construction%20blueprint%20document%20template%20preview",
    category: ["technical", "business"],
    tags: ["construction", "blueprint", "technical", "engineering"],
    popularity: 81,
    author: "Build Solutions",
    isPremium: true,
    createdAt: "2023-12-01T00:00:00Z",
    updatedAt: "2023-12-01T00:00:00Z",
    isDefault: false,
    primaryColor: "#0c4a6e",
    secondaryColor: "#0ea5e9",
    accentColor: "#facc15",
    fontFamily: "helvetica",
    headerTitle: "Construction Blueprint",
    footerText: "Technical Specifications",
    includeTimestamp: true,
    includePageNumbers: true,
    includeCoverPage: true,
    templateStyle: "technical",
    companyName: "Build Solutions Inc.",
    contactInfo: "projects@buildsolutions.example\n(555) BUILD-IT",
    watermark: "FOR REVIEW",
  },
]
