"use client";

/**
 * Visual Playground Main Page
 * Phase 33: Honest Visual Playground
 * Phase 34: Client Honest Experience Integration
 *
 * Shows all content pillars for concept generation
 */

import { useState } from "react";
import { useRouter } from "next/navigation";
import { getAllPillars, DISCLAIMERS } from "@/lib/content/pillars-config";
import { Search, Share2, Layout, Palette, AlertTriangle, Sparkles } from "lucide-react";
import CreativeLabIntroModal from "@/components/ui/onboarding/CreativeLabIntroModal";
import CreativeLabInfoDrawer, { CreativeLabInfoTrigger } from "@/components/ui/about-page/CreativeLabInfoDrawer";
import TransparencyFooter from "@/components/ui/footer/TransparencyFooter";

const ICON_MAP: Record<string, React.ReactNode> = {
  Search: <Search className="w-6 h-6" />,
  Share2: <Share2 className="w-6 h-6" />,
  Layout: <Layout className="w-6 h-6" />,
  Palette: <Palette className="w-6 h-6" />,
};

export default function VisualPlaygroundPage() {
  const router = useRouter();
  const pillars = getAllPillars();
  const [drawerOpen, setDrawerOpen] = useState(false);

  return (
    <div className="min-h-screen bg-bg-raised flex flex-col">
      {/* Onboarding Modal */}
      <CreativeLabIntroModal userId="current-user" />

      {/* Info Drawer */}
      <CreativeLabInfoDrawer
        isOpen={drawerOpen}
        onClose={() => setDrawerOpen(false)}
      />

      <div className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 w-full">
        {/* Header with Slogan */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-3">
              <Sparkles className="w-8 h-8 text-accent-600" />
              <h1 className="text-2xl font-bold text-text-primary">
                Your Creative Lab
              </h1>
            </div>
            <CreativeLabInfoTrigger onClick={() => setDrawerOpen(true)} />
          </div>
          {/* Official Slogan */}
          <p className="text-accent-600 dark:text-accent-400 font-medium mb-2">
            This is your Creative Lab — everything you see is generated in real time based on your inputs.
          </p>
          <p className="text-text-secondary text-sm">
            Explore AI-generated concept previews across different content areas
          </p>
        </div>

        {/* Global Disclaimer */}
        <div className="mb-8 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-yellow-800 dark:text-yellow-200">
                Important Notice
              </p>
              <p className="text-sm text-yellow-700 dark:text-yellow-300 mt-1">
                {DISCLAIMERS.general} These are exploratory ideas generated by AI tools,
                not guaranteed outcomes or final deliverables.
              </p>
            </div>
          </div>
        </div>

        {/* Pillars Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {pillars.map((pillar) => (
            <div
              key={pillar.id}
              className="bg-bg-card rounded-lg border border-border-subtle p-6 hover:border-accent-500 dark:hover:border-accent-500 transition-colors cursor-pointer"
              onClick={() =>
                router.push(`/client/dashboard/visual-playground/${pillar.id}`)
              }
            >
              <div className="flex items-start gap-4">
                <div className="p-3 bg-accent-100 dark:bg-accent-900/30 rounded-lg text-accent-600 dark:text-accent-400">
                  {ICON_MAP[pillar.icon] || <Sparkles className="w-6 h-6" />}
                </div>
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-text-primary mb-1">
                    {pillar.title}
                  </h3>
                  <p className="text-sm text-text-secondary mb-3">
                    {pillar.description}
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {pillar.subPillars.slice(0, 3).map((sp) => (
                      <span
                        key={sp.id}
                        className="text-xs px-2 py-1 bg-bg-hover text-text-secondary rounded"
                      >
                        {sp.title}
                      </span>
                    ))}
                    {pillar.subPillars.length > 3 && (
                      <span className="text-xs px-2 py-1 text-text-muted">
                        +{pillar.subPillars.length - 3} more
                      </span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* What This Is Not */}
        <div className="mt-8 bg-bg-hover rounded-lg p-6">
          <h3 className="font-semibold text-text-primary mb-3">
            What This Is &amp; Isn&apos;t
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <p className="text-sm font-medium text-success-600 dark:text-success-400 mb-2">
                This IS:
              </p>
              <ul className="text-sm text-text-secondary space-y-1">
                <li>• AI-generated concept exploration</li>
                <li>• Starting points for creative direction</li>
                <li>• Wireframe and layout ideas</li>
                <li>• Draft copy for review</li>
              </ul>
            </div>
            <div>
              <p className="text-sm font-medium text-error-600 dark:text-error-400 mb-2">
                This is NOT:
              </p>
              <ul className="text-sm text-text-secondary space-y-1">
                <li>• Final production-ready assets</li>
                <li>• Guaranteed performance results</li>
                <li>• Completed brand identity systems</li>
                <li>• Real testimonials or case studies</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* Transparency Footer */}
      <TransparencyFooter />
    </div>
  );
}
