# Unite-Hub - System Overview & Configuration

**Generated by**: Orchestrator Agent
**Last Updated**: 2025-11-15
**Version**: 1.0.0 (MVP)
**Status**: ⚠️ **Active Development** - Critical P0 fixes in progress

---

## UNITE-HUB – Current Application Overview

Unite-Hub is an **AI-first customer relationship and marketing automation platform** built with:
- **Frontend**: Next.js 16 + React 19 + shadcn/ui + Tailwind CSS
- **Backend**: Next.js API Routes + Supabase PostgreSQL
- **AI Layer**: Anthropic Claude API (Opus 4.5, Sonnet 4.5, Haiku 4.5)
- **Infrastructure**: Vercel (hosting) + Supabase (database + auth)

### Core Features

1. **AI Intelligence Layer**
   - Email Agent: Auto-processes emails, extracts intents, analyzes sentiment
   - Content Agent: Generates personalized marketing content (Extended Thinking)
   - Contact Intelligence: AI-powered lead scoring (0-100)
   - Orchestrator: Coordinates multi-agent workflows

2. **Email Integration**
   - Gmail OAuth 2.0 (implicit flow)
   - Email sync and sender extraction
   - Open/click tracking
   - Thread management

3. **Drip Campaign Automation**
   - Visual campaign builder
   - Conditional branching (if/else logic)
   - Trigger types: manual, new contact, tag, score threshold
   - Step types: email, wait, condition, tag, score update, webhook
   - A/B testing support

4. **Lead Scoring**
   - Email engagement frequency (40%)
   - Sentiment analysis (20%)
   - Intent quality (20%)
   - Job title/role (10%)
   - Status progression (10%)
   - Scores 60-79 = Warm | 80-100 = Hot

5. **Modern Dashboard**
   - Real-time contact management
   - Campaign performance analytics
   - Content draft review
   - Gmail integration settings
   - Dark theme, responsive design

---

## Project Structure

```
Unite-Hub/
├── .claude/                      # Claude agent configuration
│   ├── agent.md                  # Agent definitions (THIS IS CANONICAL)
│   ├── claude.md                 # System overview (THIS FILE)
│   ├── config.json               # Agent config
│   ├── mcp.json                  # MCP server config
│   ├── skills/                   # Agent skills
│   │   ├── orchestrator/
│   │   ├── email-agent/
│   │   ├── content-agent/
│   │   ├── frontend/             # To be created
│   │   └── backend/              # To be created
│   └── mcp_servers/              # To be created
│
├── src/                          # Next.js application
│   ├── app/                      # App Router (Next.js 16)
│   │   ├── dashboard/            # Dashboard routes
│   │   │   ├── overview/         # Main dashboard
│   │   │   ├── contacts/         # Contact management
│   │   │   ├── campaigns/        # Email campaigns
│   │   │   └── [21+ other pages]
│   │   ├── auth/                 # Auth callbacks
│   │   ├── api/                  # API routes (104 total)
│   │   │   ├── agents/           # AI agent endpoints
│   │   │   ├── auth/             # Auth endpoints
│   │   │   ├── campaigns/        # Campaign endpoints
│   │   │   ├── contacts/         # Contact endpoints
│   │   │   └── integrations/     # Integration endpoints
│   │   └── login/                # Login page
│   │
│   ├── components/               # React components
│   │   ├── ui/                   # shadcn/ui components
│   │   ├── client/               # Client-specific components
│   │   ├── HotLeadsPanel.tsx     # Hot leads widget
│   │   └── [100+ components]
│   │
│   ├── lib/                      # Utilities
│   │   ├── agents/               # Agent logic
│   │   │   ├── contact-intelligence.ts
│   │   │   ├── content-personalization.ts
│   │   │   └── email-processor.ts
│   │   ├── db.ts                 # Database wrapper
│   │   ├── supabase.ts           # Supabase client
│   │   └── auth.ts               # NextAuth config
│   │
│   └── contexts/                 # React contexts
│       └── AuthContext.tsx       # Auth state management
│
├── scripts/                      # CLI automation
│   ├── run-orchestrator.mjs      # Orchestrator CLI
│   ├── run-email-agent.mjs       # Email agent CLI
│   ├── run-content-agent.mjs     # Content agent CLI
│   ├── analyze-contacts.mjs      # Contact scoring
│   └── generate-content.mjs      # Content generation
│
├── public/                       # Static assets
├── supabase/                     # Supabase migrations
├── docs/                         # Documentation
├── package.json                  # Dependencies
├── .env.local                    # Environment variables
└── README.md                     # Project README

```

---

## Tech Stack Details

### Frontend
- **Next.js 16.0.1** - React framework with App Router and Turbopack
- **React 19.0.0** - UI library with Server Components
- **TypeScript 5.x** - Type-safe development
- **Tailwind CSS** - Utility-first styling
- **shadcn/ui** - Component library (50+ components)
- **Lucide React** - Icon system
- **Framer Motion** - Animations

### Backend
- **Next.js API Routes** - Serverless API endpoints (104 routes)
- **Supabase PostgreSQL** - Database with Row Level Security
- **NextAuth.js** - Authentication with SupabaseAdapter
- **Google Gmail API** - OAuth 2.0 email integration

### AI & Integrations
- **Anthropic Claude API**:
  - `claude-opus-4-5-20251101` - Content generation (Extended Thinking)
  - `claude-sonnet-4-5-20250929` - Standard operations
  - `claude-haiku-4-5-20251001` - Quick tasks
- **@anthropic-ai/sdk** v0.68.0 - Official SDK
- **googleapis** v166.0.0 - Gmail API client

### Database Schema (18 Tables)

**Core Tables**:
- `organizations` - Top-level org entities
- `users` - User accounts
- `user_profiles` - Extended user data
- `user_organizations` - User-org relationships
- `workspaces` - Team workspaces

**Contact & Email**:
- `contacts` - CRM contacts (with ai_score)
- `emails` - Email messages
- `email_opens` - Open tracking
- `email_clicks` - Click tracking
- `integrations` - OAuth integrations (Gmail, etc.)

**Campaigns**:
- `campaigns` - Email campaigns
- `drip_campaigns` - Drip sequences
- `campaign_steps` - Sequence steps
- `campaign_enrollments` - Contact enrollments
- `campaign_execution_logs` - Step execution history

**Content & AI**:
- `generatedContent` - AI-generated content drafts
- `aiMemory` - Agent memory storage
- `auditLogs` - System audit trail

---

## Current System Status

### ✅ Working Components

1. **Authentication Flow**
   - Google OAuth login (implicit flow)
   - Session management (localStorage)
   - User profile display
   - Organization fetching
   - Logout functionality

2. **User Initialization**
   - `/api/auth/initialize-user` creates profiles
   - Organization creation with owner role
   - Default workspace creation

3. **Dashboard UI**
   - Navigation layout working
   - Responsive design functional
   - Dark theme applied
   - Component rendering correct

4. **Agent Logic**
   - Email agent intent extraction ✅
   - Content agent Extended Thinking ✅
   - Orchestrator coordination ✅
   - Contact scoring algorithm ✅

### ⚠️ Critical Issues (P0 - SYSTEM BREAKING)

1. **Database Layer Broken** (`src/lib/db.ts:58`)
   ```typescript
   // Line 58 - supabaseServer is used but NOT imported
   const { data: workspace, error } = await supabaseServer // ❌ UNDEFINED
   ```
   **Impact**: ALL workspace operations fail
   **Fix**: Add `getSupabaseServer()` import and call

2. **Workspace Filtering Missing** (`src/app/dashboard/overview/page.tsx`)
   ```typescript
   // Missing workspace filter on ALL queries
   const { data: contacts } = await supabase
     .from("contacts")
     .select("ai_score, status");
     // Missing: .eq("workspace_id", workspaceId)
   ```
   **Impact**: Data isolation broken, shows all workspaces
   **Fix**: Add workspace filters to ALL dashboard queries

3. **Organization Undefined** (`src/contexts/AuthContext.tsx:110-112`)
   ```typescript
   // If orgs array is empty, currentOrganization = undefined (not null)
   setCurrentOrganization(savedOrg || orgs[0] || null);
   ```
   **Impact**: workspaceId becomes "default-org" string instead of UUID
   **Fix**: Handle empty orgs array properly

### 🔍 Audit Results Summary

- **Total API Routes**: 104
- **Dashboard Pages**: 21
- **Authentication Status**: Partially disabled (TODO comments)
- **Test Coverage**: Minimal (needs comprehensive suite)

---

## Agent Architecture

### Orchestrator → Specialist Pattern

```
User Request
    ↓
Orchestrator Agent (.claude/agent.md)
    ├─→ Email Agent (email processing)
    ├─→ Content Agent (content generation)
    ├─→ Frontend Agent (UI/route fixes)
    ├─→ Backend Agent (API/database work)
    └─→ Docs Agent (documentation updates)
```

### Agent Communication Rules

1. **Orchestrator is the single coordinator** - no peer-to-peer agent calls
2. **All agents are stateless** - state stored in database or Memory tool
3. **Workspace isolation mandatory** - all operations scoped to workspaceId
4. **Audit everything** - all actions logged to auditLogs
5. **Fail gracefully** - return error status, don't throw

See `.claude/agent.md` for complete agent definitions.

---

## Environment Configuration

### Required Environment Variables

```env
# NextAuth
NEXTAUTH_URL=http://localhost:3008
NEXTAUTH_SECRET=your-secret-key

# Supabase
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

# OAuth
GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-client-secret
GOOGLE_CALLBACK_URL=http://localhost:3008/api/integrations/gmail/callback

# Claude AI
ANTHROPIC_API_KEY=sk-ant-your-key-here

# Convex (optional - if using Convex instead of Supabase)
CONVEX_URL=https://your-convex-deployment.convex.cloud
ORG_ID=k57akqzf14r07d9q3pbf9kebvn7v7929
WORKSPACE_ID=kh72b1cng9h88691sx4x7krt2h7v7deh
```

### Port Configuration

Default: `3008` (configured in `package.json`)

```json
{
  "scripts": {
    "dev": "next dev -p 3008",
    "build": "next build",
    "start": "next start"
  }
}
```

---

## Development Workflow

### Local Development

```bash
# Install dependencies
npm install

# Start development server
npm run dev

# Run agents
npm run email-agent
npm run content-agent
npm run orchestrator
npm run workflow  # Full pipeline
npm run audit-system  # System health check

# Database
npm run check:db  # Verify schema
```

### Docker Status

**Current Status**: No Docker configuration present

**Future Consideration**: Add Dockerfile + docker-compose.yml in V2

---

## Version 1 (MVP) Scope

### What We Build (MVP)

✅ **Core Flows**:
- Email processing pipeline (Gmail → Contact Intelligence → Scoring)
- Content generation pipeline (Warm Leads → Personalized Content → Drafts)
- Orchestrator coordination (Multi-step workflows)

✅ **Dashboard Fixes**:
- Workspace filtering on all queries
- Authentication re-enabled on API routes
- Hot leads panel working end-to-end
- Contact detail pages functional

✅ **API Stabilization**:
- All 104 endpoints tested
- Authentication + authorization implemented
- Error handling standardized
- Response formats consistent

✅ **Testing**:
- Unit tests for agent functions
- Integration tests for API endpoints
- E2E test for complete user journey

### What We Do NOT Build (Post-V1)

❌ Advanced A/B testing
❌ Multi-language support
❌ Complex drip campaign branching
❌ Real-time collaboration features
❌ Mobile app
❌ Advanced analytics/reporting
❌ Custom domain support
❌ White-label options

---

## Skills & MCP Servers

### Current Skills

Located in `.claude/skills/`:
- `orchestrator/SKILL.md` - Workflow coordination
- `email-agent/SKILL.md` - Email processing
- `content-agent/SKILL.md` - Content generation

### To Be Created

- `frontend/SKILL.md` - UI/component work
- `backend/SKILL.md` - API/database work
- `docs/SKILL.md` - Documentation updates

### MCP Servers

**Current**:
- Playwright MCP configured in `.claude/mcp.json`

**To Be Added** (in `.claude/mcp_servers/`):
- File system operations (if needed)
- Git repository access (if needed)
- Database inspection (if needed)

See Claude Developer Docs for MCP server setup patterns.

---

## Claude Developer Docs Alignment

This project follows Claude Developer Docs patterns:

✅ **API Best Practices**:
- Using correct model IDs (`claude-sonnet-4-5-20250929`, not deprecated)
- Proper beta headers (`anthropic-beta: thinking-2025-11-15`)
- Extended Thinking for complex tasks (5000-10000 token budgets)
- Prompt caching disabled (not needed for short-lived requests)

✅ **Agent Architecture**:
- Progressive disclosure (load only needed context)
- Single responsibility per agent
- Tool-first approach (use Claude server tools)
- Memory management (`aiMemory` table)

✅ **Tool Usage**:
- `bash_20250124` for CLI commands
- `text_editor_20250728` for file operations
- `memory_20250818` for workflow state
- `code_execution_20250825` for quick tests

✅ **Error Handling**:
- Recoverable errors: log and continue
- Significant errors: retry with reduced scope
- Critical errors: halt and alert

✅ **Prompt Engineering**:
- Allow "I don't know" responses
- Use direct quotes for facts
- Verify with citations
- Chain-of-thought reasoning

---

## Data Flow Analysis

### Complete Flow: OAuth → Dashboard → Hot Leads

```
1. User clicks "Continue with Google" on /login
   ↓
2. Supabase OAuth (implicit flow)
   ↓
3. Redirect to /auth/callback
   ↓
4. /auth/callback detects no code parameter
   ↓
5. Redirects to /auth/implicit-callback (client-side)
   ↓
6. Client reads tokens from URL hash
   ↓
7. Supabase creates session in localStorage
   ↓
8. Redirect to /dashboard/overview
   ↓
9. AuthContext detects SIGNED_IN event
   ↓
10. Calls /api/auth/initialize-user (if first login)
    ↓
11. Fetches user profile from user_profiles table
    ↓
12. Fetches organizations from user_organizations + organizations tables
    ↓
13. Sets currentOrganization to first org
    ↓
14. Dashboard overview page renders
    ↓
15. Fetches stats from contacts + campaigns tables
    ↓
16. Passes workspaceId to HotLeadsPanel
    ↓
17. HotLeadsPanel calls /api/agents/contact-intelligence
    ↓
18. API calls getHotLeads(workspaceId)
    ↓
19. getHotLeads queries Supabase with workspace filter
    ↓
20. Calculates composite scores and filters
    ↓
21. Returns hot leads to panel
    ↓
22. Panel displays leads
```

**Critical Break Points** (TO BE FIXED):
- Step 10: User initialization not always triggered
- Step 13: If no orgs exist, currentOrganization is undefined (not null)
- Step 15: No workspace filtering breaks data isolation
- Step 16: workspaceId might be "default-org" string instead of UUID

---

## Testing Strategy

### Unit Tests (To Be Created)

```
tests/
├── agents/
│   ├── contact-intelligence.test.ts
│   ├── content-personalization.test.ts
│   └── email-processor.test.ts
├── lib/
│   └── db.test.ts
└── components/
    └── HotLeadsPanel.test.tsx
```

### Integration Tests (To Be Created)

```
tests/integration/
├── auth-flow.test.ts
├── email-pipeline.test.ts
├── content-pipeline.test.ts
└── api-endpoints.test.ts
```

### E2E Tests (To Be Created)

```
tests/e2e/
├── user-signup.spec.ts
├── dashboard-navigation.spec.ts
└── contact-management.spec.ts
```

---

## Immediate Next Steps

See **P0 Priority TODO List** below for critical fixes.

After P0 fixes:
1. Create comprehensive test suite
2. Audit remaining 100+ API endpoints
3. Test all 21 dashboard pages
4. Implement missing functionality (Send Email, View Details buttons)
5. Re-enable authentication on all API routes

---

## Design Decisions

### Decision 1: Supabase over Convex

**Context**: Project started with Convex, switched to Supabase
**Reason**: Better Next.js integration, familiar PostgreSQL, RLS policies
**Impact**: Some scripts still reference Convex (cleanup needed)
**Status**: Migration 90% complete

### Decision 2: Implicit OAuth Flow

**Context**: Could use PKCE or implicit flow
**Reason**: Simpler for MVP, fewer redirects
**Impact**: Tokens in localStorage (consider PKCE in V2 for security)
**Status**: Working, documented in OAUTH_SUCCESS.md

### Decision 3: Extended Thinking for Content Generation

**Context**: Could use standard Claude calls
**Reason**: Higher quality personalized content justifies cost
**Impact**: 5000-10000 thinking tokens per generation (~$0.10-0.20 per content)
**Status**: Working, cost-effective for warm leads

---

## Future Work (Post-V1)

### Version 2 Improvements

1. **A/B Testing Framework**
   - Subject line variants
   - Content variations
   - Send time optimization

2. **Advanced Analytics**
   - Revenue attribution
   - Conversion funnels
   - Cohort analysis

3. **Real-time Collaboration**
   - Multi-user editing
   - Live notifications
   - Team chat

4. **Mobile App**
   - React Native
   - Offline sync
   - Push notifications

5. **Enhanced Security**
   - PKCE OAuth flow
   - 2FA authentication
   - Advanced RBAC

---

## Useful References

- Main README: `README.md`
- Architecture Docs: `ARCHITECTURE.md`
- API Documentation: `API_DOCUMENTATION.md`
- System Audit: `COMPLETE_SYSTEM_AUDIT.md`
- OAuth Setup: `OAUTH_SUCCESS.md`
- Database Schema: `COMPLETE_DATABASE_SCHEMA.sql`
- Agent Definitions: `.claude/agent.md` (CANONICAL)

---

## Contact & Support

For issues and questions:
- Create GitHub issue
- Check documentation in `docs/`
- Review audit reports (COMPLETE_SYSTEM_AUDIT.md)

---

**This file is the single source of truth for the Unite-Hub system overview. Update after significant changes.**
