-- ============================================================================
-- Migration: 305_cognitive_twin_engine.sql
-- Description: Founder Cognitive Twin Engine Tables
-- Created: 2025-11-28
--
-- This migration creates tables for the Founder Cognitive Twin system,
-- enabling domain-specific health scoring, digest generation, and
-- AI-assisted decision support with scenario analysis.
-- ============================================================================

-- ============================================================================
-- 1. COGNITIVE TWIN SCORES
-- Domain-specific health scores with momentum, risks, and opportunities
-- ============================================================================

CREATE TABLE IF NOT EXISTS cognitive_twin_scores (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id uuid NOT NULL,
    founder_business_id uuid REFERENCES founder_businesses(id) ON DELETE SET NULL,
    domain text NOT NULL,
    momentum jsonb NOT NULL,
    risks jsonb DEFAULT '[]'::jsonb,
    opportunities jsonb DEFAULT '[]'::jsonb,
    overall_health numeric,
    created_at timestamptz DEFAULT now(),

    CONSTRAINT cognitive_twin_domain_check CHECK (domain IN (
        'marketing', 'sales', 'delivery', 'product', 'clients',
        'engineering', 'finance', 'founder', 'operations', 'team',
        'legal', 'compliance', 'partnerships', 'custom'
    )),
    CONSTRAINT cognitive_twin_health_check CHECK (
        overall_health IS NULL OR (overall_health >= 0 AND overall_health <= 100)
    )
);

COMMENT ON TABLE cognitive_twin_scores IS 'Domain-specific health scores for the Founder Cognitive Twin, tracking momentum, risks, and opportunities across business areas.';
COMMENT ON COLUMN cognitive_twin_scores.owner_user_id IS 'The founder user who owns this score';
COMMENT ON COLUMN cognitive_twin_scores.founder_business_id IS 'Optional link to a specific business (null = portfolio-wide)';
COMMENT ON COLUMN cognitive_twin_scores.domain IS 'Business domain: marketing, sales, delivery, product, clients, engineering, finance, founder, operations, team, legal, compliance, partnerships';
COMMENT ON COLUMN cognitive_twin_scores.momentum IS 'JSON object describing current momentum metrics and trends for the domain';
COMMENT ON COLUMN cognitive_twin_scores.risks IS 'JSON array of identified risks with severity and mitigation status';
COMMENT ON COLUMN cognitive_twin_scores.opportunities IS 'JSON array of identified opportunities with potential impact';
COMMENT ON COLUMN cognitive_twin_scores.overall_health IS 'Composite health score (0-100) for this domain';

-- Indexes for cognitive_twin_scores
CREATE INDEX IF NOT EXISTS idx_cognitive_twin_scores_owner_domain
    ON cognitive_twin_scores (owner_user_id, domain, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cognitive_twin_scores_business
    ON cognitive_twin_scores (founder_business_id, domain, created_at DESC)
    WHERE founder_business_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cognitive_twin_scores_health
    ON cognitive_twin_scores (overall_health DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cognitive_twin_scores_created
    ON cognitive_twin_scores (created_at DESC);

-- ============================================================================
-- 2. COGNITIVE TWIN DIGESTS
-- Periodic digest summaries (daily, weekly, monthly)
-- ============================================================================

CREATE TABLE IF NOT EXISTS cognitive_twin_digests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id uuid NOT NULL,
    digest_type text NOT NULL,
    digest_md text NOT NULL,
    key_metrics jsonb DEFAULT '{}'::jsonb,
    action_items jsonb DEFAULT '[]'::jsonb,
    created_at timestamptz DEFAULT now(),

    CONSTRAINT cognitive_twin_digest_type_check CHECK (digest_type IN (
        'daily', 'weekly', 'monthly', 'quarterly', 'annual',
        'on_demand', 'crisis', 'milestone', 'custom'
    ))
);

COMMENT ON TABLE cognitive_twin_digests IS 'Periodic digest summaries generated by the Cognitive Twin, providing founder briefings at various intervals.';
COMMENT ON COLUMN cognitive_twin_digests.owner_user_id IS 'The founder user who owns this digest';
COMMENT ON COLUMN cognitive_twin_digests.digest_type IS 'Digest frequency: daily, weekly, monthly, quarterly, annual, on_demand, crisis, milestone';
COMMENT ON COLUMN cognitive_twin_digests.digest_md IS 'Full digest content in Markdown format';
COMMENT ON COLUMN cognitive_twin_digests.key_metrics IS 'JSON object of key metrics highlighted in this digest';
COMMENT ON COLUMN cognitive_twin_digests.action_items IS 'JSON array of recommended action items with priority and deadline';

-- Indexes for cognitive_twin_digests
CREATE INDEX IF NOT EXISTS idx_cognitive_twin_digests_owner_type
    ON cognitive_twin_digests (owner_user_id, digest_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cognitive_twin_digests_created
    ON cognitive_twin_digests (created_at DESC);

-- ============================================================================
-- 3. COGNITIVE TWIN DECISIONS
-- AI-assisted decision support with scenario analysis
-- ============================================================================

CREATE TABLE IF NOT EXISTS cognitive_twin_decisions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id uuid NOT NULL,
    founder_business_id uuid REFERENCES founder_businesses(id) ON DELETE SET NULL,
    decision_type text NOT NULL,
    scenario jsonb NOT NULL,
    options jsonb DEFAULT '[]'::jsonb,
    outcome jsonb,
    ai_recommendation text,
    human_decision text,
    decided_at timestamptz,
    created_at timestamptz DEFAULT now(),

    CONSTRAINT cognitive_twin_decision_type_check CHECK (decision_type IN (
        'strategic', 'tactical', 'operational', 'financial', 'hiring',
        'product', 'pricing', 'partnership', 'investment', 'expansion',
        'crisis', 'pivot', 'exit', 'custom'
    ))
);

COMMENT ON TABLE cognitive_twin_decisions IS 'AI-assisted decision support with scenario analysis and outcome tracking.';
COMMENT ON COLUMN cognitive_twin_decisions.owner_user_id IS 'The founder user who owns this decision';
COMMENT ON COLUMN cognitive_twin_decisions.founder_business_id IS 'Optional link to a specific business';
COMMENT ON COLUMN cognitive_twin_decisions.decision_type IS 'Type: strategic, tactical, operational, financial, hiring, product, pricing, partnership, investment, expansion, crisis, pivot, exit';
COMMENT ON COLUMN cognitive_twin_decisions.scenario IS 'JSON object describing the decision scenario, context, and constraints';
COMMENT ON COLUMN cognitive_twin_decisions.options IS 'JSON array of possible options with pros, cons, and projected outcomes';
COMMENT ON COLUMN cognitive_twin_decisions.outcome IS 'JSON object recording the actual outcome after decision was made';
COMMENT ON COLUMN cognitive_twin_decisions.ai_recommendation IS 'AI-generated recommendation text';
COMMENT ON COLUMN cognitive_twin_decisions.human_decision IS 'The actual decision made by the founder';
COMMENT ON COLUMN cognitive_twin_decisions.decided_at IS 'When the decision was finalized';

-- Indexes for cognitive_twin_decisions
CREATE INDEX IF NOT EXISTS idx_cognitive_twin_decisions_owner_type
    ON cognitive_twin_decisions (owner_user_id, decision_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_cognitive_twin_decisions_business
    ON cognitive_twin_decisions (founder_business_id, created_at DESC)
    WHERE founder_business_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_cognitive_twin_decisions_pending
    ON cognitive_twin_decisions (owner_user_id, created_at DESC)
    WHERE decided_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_cognitive_twin_decisions_created
    ON cognitive_twin_decisions (created_at DESC);

-- ============================================================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE cognitive_twin_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE cognitive_twin_digests ENABLE ROW LEVEL SECURITY;
ALTER TABLE cognitive_twin_decisions ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- RLS POLICIES: cognitive_twin_scores
-- ============================================================================

DROP POLICY IF EXISTS "cognitive_twin_scores_select_own" ON cognitive_twin_scores;
CREATE POLICY "cognitive_twin_scores_select_own" ON cognitive_twin_scores
    FOR SELECT USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_scores_insert_own" ON cognitive_twin_scores;
CREATE POLICY "cognitive_twin_scores_insert_own" ON cognitive_twin_scores
    FOR INSERT WITH CHECK (owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_scores_update_own" ON cognitive_twin_scores;
CREATE POLICY "cognitive_twin_scores_update_own" ON cognitive_twin_scores
    FOR UPDATE USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_scores_delete_own" ON cognitive_twin_scores;
CREATE POLICY "cognitive_twin_scores_delete_own" ON cognitive_twin_scores
    FOR DELETE USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

-- ============================================================================
-- RLS POLICIES: cognitive_twin_digests
-- ============================================================================

DROP POLICY IF EXISTS "cognitive_twin_digests_select_own" ON cognitive_twin_digests;
CREATE POLICY "cognitive_twin_digests_select_own" ON cognitive_twin_digests
    FOR SELECT USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_digests_insert_own" ON cognitive_twin_digests;
CREATE POLICY "cognitive_twin_digests_insert_own" ON cognitive_twin_digests
    FOR INSERT WITH CHECK (owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_digests_update_own" ON cognitive_twin_digests;
CREATE POLICY "cognitive_twin_digests_update_own" ON cognitive_twin_digests
    FOR UPDATE USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_digests_delete_own" ON cognitive_twin_digests;
CREATE POLICY "cognitive_twin_digests_delete_own" ON cognitive_twin_digests
    FOR DELETE USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

-- ============================================================================
-- RLS POLICIES: cognitive_twin_decisions
-- ============================================================================

DROP POLICY IF EXISTS "cognitive_twin_decisions_select_own" ON cognitive_twin_decisions;
CREATE POLICY "cognitive_twin_decisions_select_own" ON cognitive_twin_decisions
    FOR SELECT USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_decisions_insert_own" ON cognitive_twin_decisions;
CREATE POLICY "cognitive_twin_decisions_insert_own" ON cognitive_twin_decisions
    FOR INSERT WITH CHECK (owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_decisions_update_own" ON cognitive_twin_decisions;
CREATE POLICY "cognitive_twin_decisions_update_own" ON cognitive_twin_decisions
    FOR UPDATE USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

DROP POLICY IF EXISTS "cognitive_twin_decisions_delete_own" ON cognitive_twin_decisions;
CREATE POLICY "cognitive_twin_decisions_delete_own" ON cognitive_twin_decisions
    FOR DELETE USING (workspace_id = current_setting('app.current_workspace_id')::uuid AND owner_user_id = auth.uid());

-- ============================================================================
-- GRANTS
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON cognitive_twin_scores TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON cognitive_twin_digests TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON cognitive_twin_decisions TO authenticated;

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Get latest domain scores for a founder
CREATE OR REPLACE FUNCTION get_cognitive_twin_dashboard(p_owner_user_id uuid)
RETURNS TABLE (
    domain text,
    overall_health numeric,
    momentum jsonb,
    risk_count int,
    opportunity_count int,
    last_updated timestamptz
) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT ON (cts.domain)
        cts.domain,
        cts.overall_health,
        cts.momentum,
        jsonb_array_length(cts.risks)::int AS risk_count,
        jsonb_array_length(cts.opportunities)::int AS opportunity_count,
        cts.created_at AS last_updated
    FROM cognitive_twin_scores cts
    WHERE cts.owner_user_id = p_owner_user_id
    ORDER BY cts.domain, cts.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get portfolio-wide health summary
CREATE OR REPLACE FUNCTION get_portfolio_health_summary(p_owner_user_id uuid)
RETURNS TABLE (
    avg_health numeric,
    domains_critical int,
    domains_warning int,
    domains_healthy int,
    total_risks int,
    total_opportunities int
) AS $$
BEGIN
    RETURN QUERY
    WITH latest_scores AS (
        SELECT DISTINCT ON (domain)
            domain,
            overall_health,
            jsonb_array_length(risks) AS risk_count,
            jsonb_array_length(opportunities) AS opp_count
        FROM cognitive_twin_scores
        WHERE owner_user_id = p_owner_user_id
        ORDER BY domain, created_at DESC
    )
    SELECT
        ROUND(AVG(overall_health)::numeric, 1) AS avg_health,
        COUNT(*) FILTER (WHERE overall_health < 40)::int AS domains_critical,
        COUNT(*) FILTER (WHERE overall_health >= 40 AND overall_health < 70)::int AS domains_warning,
        COUNT(*) FILTER (WHERE overall_health >= 70)::int AS domains_healthy,
        COALESCE(SUM(risk_count), 0)::int AS total_risks,
        COALESCE(SUM(opp_count), 0)::int AS total_opportunities
    FROM latest_scores;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get pending decisions
CREATE OR REPLACE FUNCTION get_pending_decisions(p_owner_user_id uuid)
RETURNS TABLE (
    id uuid,
    decision_type text,
    scenario_title text,
    options_count int,
    ai_recommendation text,
    days_pending int,
    created_at timestamptz
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        ctd.id,
        ctd.decision_type,
        ctd.scenario->>'title' AS scenario_title,
        jsonb_array_length(ctd.options)::int AS options_count,
        ctd.ai_recommendation,
        EXTRACT(DAY FROM (now() - ctd.created_at))::int AS days_pending,
        ctd.created_at
    FROM cognitive_twin_decisions ctd
    WHERE ctd.owner_user_id = p_owner_user_id
    AND ctd.decided_at IS NULL
    ORDER BY ctd.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Record a decision outcome
CREATE OR REPLACE FUNCTION record_decision_outcome(
    p_decision_id uuid,
    p_human_decision text,
    p_outcome jsonb DEFAULT NULL
)
RETURNS void AS $$
BEGIN
    UPDATE cognitive_twin_decisions
    SET
        human_decision = p_human_decision,
        outcome = COALESCE(p_outcome, outcome),
        decided_at = now()
    WHERE id = p_decision_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Generate domain health score
CREATE OR REPLACE FUNCTION calculate_domain_health(
    p_owner_user_id uuid,
    p_domain text,
    p_business_id uuid DEFAULT NULL
)
RETURNS numeric AS $$
DECLARE
    v_base_score numeric := 50;
    v_momentum_bonus numeric := 0;
    v_risk_penalty numeric := 0;
    v_opportunity_bonus numeric := 0;
    v_recent_decision_bonus numeric := 0;
    v_final_score numeric;
BEGIN
    -- Get recent scores for this domain
    SELECT
        COALESCE(
            CASE
                WHEN momentum->>'trend' = 'improving' THEN 15
                WHEN momentum->>'trend' = 'stable' THEN 5
                WHEN momentum->>'trend' = 'declining' THEN -10
                ELSE 0
            END,
            0
        ),
        COALESCE(jsonb_array_length(risks) * -5, 0),
        COALESCE(jsonb_array_length(opportunities) * 3, 0)
    INTO v_momentum_bonus, v_risk_penalty, v_opportunity_bonus
    FROM cognitive_twin_scores
    WHERE owner_user_id = p_owner_user_id
    AND domain = p_domain
    AND (p_business_id IS NULL OR founder_business_id = p_business_id)
    ORDER BY created_at DESC
    LIMIT 1;

    -- Check for recent positive decisions
    SELECT
        CASE WHEN COUNT(*) > 0 THEN 5 ELSE 0 END
    INTO v_recent_decision_bonus
    FROM cognitive_twin_decisions
    WHERE owner_user_id = p_owner_user_id
    AND decided_at > now() - INTERVAL '30 days'
    AND outcome->>'success' = 'true';

    -- Calculate final score
    v_final_score := GREATEST(0, LEAST(100,
        v_base_score +
        v_momentum_bonus +
        v_risk_penalty +
        v_opportunity_bonus +
        v_recent_decision_bonus
    ));

    RETURN v_final_score;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get digest history
CREATE OR REPLACE FUNCTION get_digest_history(
    p_owner_user_id uuid,
    p_digest_type text DEFAULT NULL,
    p_limit int DEFAULT 10
)
RETURNS TABLE (
    id uuid,
    digest_type text,
    key_metrics jsonb,
    action_item_count int,
    created_at timestamptz
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        ctd.id,
        ctd.digest_type,
        ctd.key_metrics,
        jsonb_array_length(ctd.action_items)::int AS action_item_count,
        ctd.created_at
    FROM cognitive_twin_digests ctd
    WHERE ctd.owner_user_id = p_owner_user_id
    AND (p_digest_type IS NULL OR ctd.digest_type = p_digest_type)
    ORDER BY ctd.created_at DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================

DO $$
BEGIN
    RAISE NOTICE 'Migration 305_cognitive_twin_engine.sql completed successfully';
    RAISE NOTICE 'Created tables: cognitive_twin_scores, cognitive_twin_digests, cognitive_twin_decisions';
    RAISE NOTICE 'RLS enabled and policies created for all tables';
END $$;
