#!/bin/bash

# =============================================================================
# Type Generation Script for Unite-Hub
# =============================================================================
# Generates TypeScript types from Supabase database schema
# Uses: Supabase CLI
# Output: src/types/database.generated.ts
# =============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}==============================================================================${NC}"
echo -e "${BLUE}Unite-Hub Type Generation Pipeline${NC}"
echo -e "${BLUE}==============================================================================${NC}"

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo -e "${YELLOW}⚠️  Supabase CLI not found. Installing...${NC}"

    # Install Supabase CLI (platform-specific)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        brew install supabase/tap/supabase
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        brew install supabase/tap/supabase
    elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
        # Windows (Git Bash/MSYS/MinGW)
        echo -e "${YELLOW}For Windows, install Supabase CLI manually:${NC}"
        echo -e "${YELLOW}scoop bucket add supabase https://github.com/supabase/scoop-bucket.git${NC}"
        echo -e "${YELLOW}scoop install supabase${NC}"
        echo -e "${RED}❌ Please install Supabase CLI and re-run this script${NC}"
        exit 1
    else
        echo -e "${RED}❌ Unsupported platform: $OSTYPE${NC}"
        exit 1
    fi
fi

echo -e "${GREEN}✅ Supabase CLI found${NC}"

# Verify environment variables
if [ -z "$NEXT_PUBLIC_SUPABASE_URL" ] || [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
    echo -e "${RED}❌ Missing required environment variables:${NC}"
    echo -e "${RED}   - NEXT_PUBLIC_SUPABASE_URL${NC}"
    echo -e "${RED}   - SUPABASE_SERVICE_ROLE_KEY${NC}"
    echo -e "${YELLOW}Please add these to your .env.local file${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Environment variables validated${NC}"

# Extract project reference from Supabase URL
PROJECT_REF=$(echo "$NEXT_PUBLIC_SUPABASE_URL" | sed -E 's|https://([^.]+)\.supabase\.co|\1|')

if [ -z "$PROJECT_REF" ]; then
    echo -e "${RED}❌ Could not extract project reference from NEXT_PUBLIC_SUPABASE_URL${NC}"
    echo -e "${RED}   Expected format: https://PROJECT_REF.supabase.co${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Project reference: ${PROJECT_REF}${NC}"

# Create output directory if it doesn't exist
OUTPUT_DIR="src/types"
OUTPUT_FILE="${OUTPUT_DIR}/database.generated.ts"

mkdir -p "$OUTPUT_DIR"

echo -e "${BLUE}📝 Generating types from Supabase schema...${NC}"

# Generate types using Supabase CLI
# Note: This requires Supabase CLI to be linked to your project
# Run: supabase login (first time only)
# Run: supabase link --project-ref $PROJECT_REF (first time only)

if [ ! -f ".supabase/config.toml" ]; then
    echo -e "${YELLOW}⚠️  Supabase project not linked. Linking now...${NC}"
    supabase link --project-ref "$PROJECT_REF"
fi

# Generate types
supabase gen types typescript --linked > "$OUTPUT_FILE"

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Types generated successfully: ${OUTPUT_FILE}${NC}"

    # Add header comment to generated file
    TEMP_FILE=$(mktemp)
    cat > "$TEMP_FILE" << 'EOF'
/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from the Supabase database schema.
 *
 * To regenerate:
 *   npm run types:generate
 *
 * Last generated: TIMESTAMP
 */

EOF

    # Replace TIMESTAMP
    sed -i "s/TIMESTAMP/$(date -u +"%Y-%m-%d %H:%M:%S UTC")/" "$TEMP_FILE"

    # Append generated types
    cat "$OUTPUT_FILE" >> "$TEMP_FILE"

    # Replace original file
    mv "$TEMP_FILE" "$OUTPUT_FILE"

    echo -e "${GREEN}✅ Header added to generated types${NC}"

    # Validate TypeScript compilation
    echo -e "${BLUE}🔍 Validating generated types...${NC}"

    if npx tsc --noEmit --skipLibCheck "$OUTPUT_FILE" 2>&1; then
        echo -e "${GREEN}✅ Type validation passed${NC}"
    else
        echo -e "${YELLOW}⚠️  Type validation warnings (non-fatal)${NC}"
    fi

    # Show file stats
    LINES=$(wc -l < "$OUTPUT_FILE")
    SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
    echo -e "${GREEN}📊 Generated ${LINES} lines (${SIZE})${NC}"

    echo -e "${BLUE}==============================================================================${NC}"
    echo -e "${GREEN}✅ Type generation complete!${NC}"
    echo -e "${BLUE}==============================================================================${NC}"

else
    echo -e "${RED}❌ Type generation failed${NC}"
    exit 1
fi
