/**
 * Cron: Founder Weekly Briefing
 * GET /api/cron/founder-briefing
 *
 * Runs every Monday at 21:00 UTC (07:00 AEST Tuesday — note: UTC+10)
 * Schedule in vercel.json: "0 21 * * 0"  (Sunday 21:00 UTC = Monday 07:00 AEST)
 *
 * Vercel Cron sends: Authorization: Bearer <CRON_SECRET>
 */

import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';
import { supabaseAdmin } from '@/lib/supabase';
import { generateWeeklyBriefing } from '@/lib/services/founderWeeklyBriefing';

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

export async function GET(req: NextRequest) {
  // ── Auth ────────────────────────────────────────────────────────────────────
  if (req.headers.get('authorization') !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    // ── Resolve founder user ID ─────────────────────────────────────────────
    let ownerId: string | null = process.env.FOUNDER_USER_ID ?? null;

    if (!ownerId) {
      const email = process.env.FOUNDER_EMAIL;
      if (email) {
        const { data } = await supabaseAdmin.auth.admin.listUsers();
        const user = data?.users?.find((u) => u.email === email);
        ownerId = user?.id ?? null;
      }
    }

    if (!ownerId) {
      console.warn('[cron/founder-briefing] FOUNDER_USER_ID or FOUNDER_EMAIL not configured');
      return NextResponse.json(
        { error: 'FOUNDER_USER_ID or FOUNDER_EMAIL not configured' },
        { status: 200 }
      );
    }

    // ── Generate (or fetch cached) briefing ──────────────────────────────────
    const briefing = await generateWeeklyBriefing(ownerId);

    // ── Email delivery via Resend ────────────────────────────────────────────
    let deliveredEmail = false;
    const founderEmail = process.env.FOUNDER_EMAIL;

    if (founderEmail && process.env.RESEND_API_KEY && !briefing.delivered_email) {
      try {
        const resend = new Resend(process.env.RESEND_API_KEY);

        await resend.emails.send({
          from: 'Phill OS <noreply@unite-group.in>',
          to: founderEmail,
          subject: `Phill OS: Weekly Briefing — ${briefing.week_starting}`,
          html: `<div style="font-family:monospace;background:#050505;color:#ffffff;padding:24px;max-width:600px;margin:0 auto">
  <h2 style="color:#00F5FF;margin-bottom:16px;font-size:18px;letter-spacing:0.05em">
    PHILL OS — WEEKLY BRIEFING
  </h2>
  <p style="color:#888;font-size:12px;margin-bottom:20px">
    Week of ${briefing.week_starting}
  </p>
  <div style="border-top:1px solid #1a1a1a;padding-top:16px;color:#e0e0e0;line-height:1.6">
    ${briefing.summary_html}
  </div>
  <p style="color:#444;font-size:11px;margin-top:24px;border-top:1px solid #1a1a1a;padding-top:12px">
    Generated by Unite-Group CRM · Phill OS
  </p>
</div>`,
          text: briefing.summary_text,
        });

        deliveredEmail = true;

        await supabaseAdmin
          .from('founder_weekly_briefings')
          .update({ delivered_email: true })
          .eq('id', briefing.id);
      } catch (emailErr) {
        console.error('[cron/founder-briefing] Email delivery failed:', emailErr);
      }
    }

    return NextResponse.json({
      success: true,
      briefingId: briefing.id,
      weekStarting: briefing.week_starting,
      deliveredEmail,
    });
  } catch (err) {
    console.error('[cron/founder-briefing]', err);
    // Always return 200 for cron endpoints — non-200 causes Vercel to retry
    return NextResponse.json({ success: false, error: String(err) }, { status: 200 });
  }
}
