-- Migration: 406_synthex_website_previews
-- Description: Create table for storing AI-generated website previews
-- Created: 2024-12-04

-- ============================================================================
-- Table: synthex_website_previews
-- ============================================================================
-- Stores AI-generated website previews that clients can approve or request revisions

CREATE TABLE IF NOT EXISTS synthex_website_previews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES synthex_tenants(id) ON DELETE CASCADE,
  brand_id UUID REFERENCES synthex_brands(id) ON DELETE SET NULL,

  -- Status tracking
  status TEXT NOT NULL DEFAULT 'generating' CHECK (
    status IN ('generating', 'ready', 'approved', 'rejected', 'revision_requested')
  ),

  -- Generated content (stored as JSONB)
  copy_json JSONB NOT NULL DEFAULT '{}',
  hero_image_json JSONB DEFAULT NULL,
  color_scheme_json JSONB NOT NULL DEFAULT '{}',

  -- Metadata
  generation_prompt_hints TEXT,
  revision_notes TEXT,
  revision_count INTEGER DEFAULT 0,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,

  -- Constraints
  CONSTRAINT valid_copy_json CHECK (jsonb_typeof(copy_json) = 'object'),
  CONSTRAINT valid_color_scheme CHECK (jsonb_typeof(color_scheme_json) = 'object')
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Fast lookup by tenant
DROP INDEX IF EXISTS idx_website_previews_tenant;
CREATE INDEX IF NOT EXISTS idx_website_previews_tenant
  ON synthex_website_previews(tenant_id);

-- Find approved previews quickly
DROP INDEX IF EXISTS idx_website_previews_status;
CREATE INDEX IF NOT EXISTS idx_website_previews_status
  ON synthex_website_previews(status);

-- Latest preview per tenant
DROP INDEX IF EXISTS idx_website_previews_tenant_latest;
CREATE INDEX IF NOT EXISTS idx_website_previews_tenant_latest
  ON synthex_website_previews(tenant_id, created_at DESC);

-- ============================================================================
-- RLS Policies
-- ============================================================================

ALTER TABLE synthex_website_previews ENABLE ROW LEVEL SECURITY;

-- Tenant owners can view their own previews
DROP POLICY IF EXISTS "Tenant owners can view previews" ON synthex_website_previews;
CREATE POLICY "Tenant owners can view previews"
  ON synthex_website_previews
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM synthex_tenants
      WHERE synthex_tenants.id = synthex_website_previews.tenant_id
      AND synthex_tenants.owner_user_id = auth.uid()
    )
  );

-- Tenant owners can update their own previews (approve, request revision)
DROP POLICY IF EXISTS "Tenant owners can update previews" ON synthex_website_previews;
CREATE POLICY "Tenant owners can update previews"
  ON synthex_website_previews
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM synthex_tenants
      WHERE synthex_tenants.id = synthex_website_previews.tenant_id
      AND synthex_tenants.owner_user_id = auth.uid()
    )
  );

-- Only service role can insert (previews are generated by the system)
DROP POLICY IF EXISTS "Service role can insert previews" ON synthex_website_previews;
CREATE POLICY "Service role can insert previews"
  ON synthex_website_previews
  FOR INSERT
  WITH CHECK (true);

-- ============================================================================
-- Triggers
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_website_preview_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_website_preview_timestamp ON synthex_website_previews;
CREATE TRIGGER trigger_update_website_preview_timestamp
  BEFORE UPDATE ON synthex_website_previews
  FOR EACH ROW
  EXECUTE FUNCTION update_website_preview_timestamp();

-- Increment revision count when status changes to revision_requested
CREATE OR REPLACE FUNCTION increment_preview_revision_count()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'revision_requested' AND OLD.status != 'revision_requested' THEN
    NEW.revision_count = COALESCE(OLD.revision_count, 0) + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_increment_revision_count ON synthex_website_previews;
CREATE TRIGGER trigger_increment_revision_count
  BEFORE UPDATE ON synthex_website_previews
  FOR EACH ROW
  EXECUTE FUNCTION increment_preview_revision_count();

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE synthex_website_previews IS 'AI-generated website previews for Synthex clients';
COMMENT ON COLUMN synthex_website_previews.copy_json IS 'Landing page copy generated by AI Phill (Claude)';
COMMENT ON COLUMN synthex_website_previews.hero_image_json IS 'Hero image generated by Gemini (base64 + metadata)';
COMMENT ON COLUMN synthex_website_previews.color_scheme_json IS 'Industry-specific color palette';
COMMENT ON COLUMN synthex_website_previews.revision_notes IS 'Client feedback for revision requests';
