-- Migration: 407_synthex_seo_reports
-- Description: Create table for storing Claude-generated SEO analysis reports
-- Created: 2025-12-06
-- Phase: B2 - Synthex SEO Reports

-- ============================================================================
-- Table: synthex_seo_reports
-- ============================================================================
-- Stores full history of AI-generated SEO analysis reports for Synthex clients.
-- Each report is a snapshot in time, never overwritten.
-- Multi-tenant scoped by tenant_id with optional brand_id for per-brand reports.

CREATE TABLE IF NOT EXISTS synthex_seo_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Multi-tenant scope
  tenant_id UUID NOT NULL REFERENCES synthex_tenants(id) ON DELETE CASCADE,
  brand_id UUID REFERENCES synthex_brands(id) ON DELETE SET NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Analysis target
  target_url TEXT NOT NULL,
  keywords TEXT[] NULL,
  competitors TEXT[] NULL,

  -- Analysis results
  score NUMERIC(5,2) NULL CHECK (score >= 0 AND score <= 100),
  issues JSONB NULL,
  recommendations JSONB NULL,

  -- Raw output for debugging/history
  raw_output TEXT NULL,

  -- Agent metadata
  agent_version TEXT NULL,
  meta JSONB NULL,

  -- Constraints
  CONSTRAINT valid_issues CHECK (issues IS NULL OR jsonb_typeof(issues) = 'array'),
  CONSTRAINT valid_recommendations CHECK (recommendations IS NULL OR jsonb_typeof(recommendations) = 'array'),
  CONSTRAINT valid_meta CHECK (meta IS NULL OR jsonb_typeof(meta) = 'object')
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Primary query pattern: list reports by tenant/brand ordered by date
DROP INDEX IF EXISTS idx_seo_reports_tenant_created;
CREATE INDEX IF NOT EXISTS idx_seo_reports_tenant_created
  ON synthex_seo_reports(tenant_id, created_at DESC);

-- Filter by tenant + brand
DROP INDEX IF EXISTS idx_seo_reports_tenant_brand_created;
CREATE INDEX IF NOT EXISTS idx_seo_reports_tenant_brand_created
  ON synthex_seo_reports(tenant_id, brand_id, created_at DESC);

-- Look up by target URL
DROP INDEX IF EXISTS idx_seo_reports_target_url;
CREATE INDEX IF NOT EXISTS idx_seo_reports_target_url
  ON synthex_seo_reports(target_url, created_at DESC);

-- Filter by score for dashboards
DROP INDEX IF EXISTS idx_seo_reports_score;
CREATE INDEX IF NOT EXISTS idx_seo_reports_score
  ON synthex_seo_reports(tenant_id, score DESC NULLS LAST);

-- ============================================================================
-- RLS Policies
-- ============================================================================

ALTER TABLE synthex_seo_reports ENABLE ROW LEVEL SECURITY;

-- Tenant owners can view their own reports
DROP POLICY IF EXISTS "Tenant owners can view SEO reports" ON synthex_seo_reports;
CREATE POLICY "Tenant owners can view SEO reports"
  ON synthex_seo_reports
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM synthex_tenants
      WHERE synthex_tenants.id = synthex_seo_reports.tenant_id
      AND synthex_tenants.owner_user_id = auth.uid()
    )
  );

-- Tenant owners can delete their own reports
DROP POLICY IF EXISTS "Tenant owners can delete SEO reports" ON synthex_seo_reports;
CREATE POLICY "Tenant owners can delete SEO reports"
  ON synthex_seo_reports
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM synthex_tenants
      WHERE synthex_tenants.id = synthex_seo_reports.tenant_id
      AND synthex_tenants.owner_user_id = auth.uid()
    )
  );

-- Service role can insert reports (generated by the system)
DROP POLICY IF EXISTS "Service role can insert SEO reports" ON synthex_seo_reports;
CREATE POLICY "Service role can insert SEO reports"
  ON synthex_seo_reports
  FOR INSERT
  WITH CHECK (true);

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE synthex_seo_reports IS 'AI-generated SEO analysis reports for Synthex clients (Claude Sonnet)';
COMMENT ON COLUMN synthex_seo_reports.tenant_id IS 'Synthex tenant (business) this report belongs to';
COMMENT ON COLUMN synthex_seo_reports.brand_id IS 'Optional brand within tenant (for multi-brand businesses)';
COMMENT ON COLUMN synthex_seo_reports.user_id IS 'User who triggered the analysis';
COMMENT ON COLUMN synthex_seo_reports.target_url IS 'URL that was analyzed';
COMMENT ON COLUMN synthex_seo_reports.keywords IS 'Keywords analyzed in this report';
COMMENT ON COLUMN synthex_seo_reports.competitors IS 'Competitor URLs/domains analyzed';
COMMENT ON COLUMN synthex_seo_reports.score IS 'Overall SEO health score (0-100)';
COMMENT ON COLUMN synthex_seo_reports.issues IS 'Array of {category, description, severity, impact} objects';
COMMENT ON COLUMN synthex_seo_reports.recommendations IS 'Array of {action, impact, priority, effort} objects';
COMMENT ON COLUMN synthex_seo_reports.raw_output IS 'Raw LLM response for debugging';
COMMENT ON COLUMN synthex_seo_reports.agent_version IS 'Version identifier (e.g., sonnet-4.5-seo-v1)';
COMMENT ON COLUMN synthex_seo_reports.meta IS 'Flexible metadata (scan_type, language, region, etc.)';

-- ============================================================================
-- Migration Complete
-- ============================================================================
-- Next steps:
-- 1. Apply this migration via Supabase Dashboard > SQL Editor
-- 2. Create seoService.ts for DB access layer
-- 3. Create API routes at /api/synthex/seo/run and /api/synthex/seo/reports
-- 4. Wire up the /synthex/seo page to use these APIs
