/**
 * CSP Nonce Demo Page
 *
 * Demonstrates correct usage of CSP nonces with inline scripts and styles.
 * This page shows how to use the JsonLdScript, Script, and InlineStyle components.
 *
 * USAGE: Visit /examples/csp-nonce-demo in development to see CSP nonces in action
 *
 * TESTING:
 * 1. Check browser DevTools → Network → Response Headers for CSP header
 * 2. View page source to see nonce attributes on scripts
 * 3. Check Console for no CSP violations
 */

import { headers } from 'next/headers';
import { getNonceFromHeaders } from '@/lib/security/csp';
import { JsonLdScript, Script, InlineStyle } from '@/components/security';

export default function CSPNonceDemo() {
  // Get nonce from middleware (only available in Server Components)
  const nonce = getNonceFromHeaders(headers());

  // Example structured data
  const organizationSchema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": "https://unite-hub.com/#organization",
    "name": "Unite-Hub",
    "url": "https://unite-hub.com/",
    "description": "AI-first CRM and marketing automation platform",
    "logo": "https://unite-hub.com/logo.png",
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://unite-hub.com/"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "Examples",
        "item": "https://unite-hub.com/examples"
      },
      {
        "@type": "ListItem",
        "position": 3,
        "name": "CSP Nonce Demo",
        "item": "https://unite-hub.com/examples/csp-nonce-demo"
      }
    ]
  };

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white rounded-lg shadow-lg p-8">
          {/* Header */}
          <h1 className="text-3xl font-bold text-gray-900 mb-4">
            CSP Nonce Demo
          </h1>
          <p className="text-gray-600 mb-8">
            This page demonstrates CSP nonce usage. Check browser DevTools to see:
          </p>

          {/* Instructions */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8">
            <h2 className="text-xl font-semibold text-blue-900 mb-3">
              How to Verify CSP Nonces
            </h2>
            <ol className="list-decimal list-inside space-y-2 text-blue-800">
              <li>
                Open DevTools → <strong>Network</strong> tab → Reload page
              </li>
              <li>
                Click on this page request → <strong>Headers</strong> tab
              </li>
              <li>
                Find <code className="bg-blue-100 px-1 rounded">Content-Security-Policy</code> header
              </li>
              <li>
                Verify it contains <code className="bg-blue-100 px-1 rounded">'nonce-...'</code> in script-src
              </li>
              <li>
                View page source (Ctrl+U / Cmd+U)
              </li>
              <li>
                Verify all <code className="bg-blue-100 px-1 rounded">&lt;script&gt;</code> tags have <code className="bg-blue-100 px-1 rounded">nonce="..."</code> attribute
              </li>
              <li>
                Check <strong>Console</strong> tab - should have NO CSP violations
              </li>
            </ol>
          </div>

          {/* Current Nonce */}
          <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
            <h2 className="text-xl font-semibold text-green-900 mb-3">
              Current Nonce Value
            </h2>
            <p className="text-green-800 mb-2">
              This nonce is unique per request and generated by the middleware:
            </p>
            <code className="block bg-green-100 text-green-900 p-3 rounded font-mono text-sm break-all">
              {nonce || 'No nonce available (not in Server Component)'}
            </code>
            <p className="text-green-700 text-sm mt-2">
              🔒 This nonce is cryptographically random and changes on every page load.
            </p>
          </div>

          {/* Example 1: JSON-LD Scripts */}
          <div className="bg-purple-50 border border-purple-200 rounded-lg p-6 mb-8">
            <h2 className="text-xl font-semibold text-purple-900 mb-3">
              Example 1: JSON-LD Structured Data
            </h2>
            <p className="text-purple-800 mb-4">
              Using <code className="bg-purple-100 px-1 rounded">JsonLdScript</code> component for Schema.org markup:
            </p>
            <pre className="bg-purple-100 text-purple-900 p-4 rounded text-xs overflow-x-auto">
{`import { JsonLdScript } from '@/components/security';

const schema = { "@context": "https://schema.org", ... };
<JsonLdScript nonce={nonce} data={schema} />`}
            </pre>
            <p className="text-purple-700 text-sm mt-3">
              ✅ Two JSON-LD scripts added to this page (Organization + Breadcrumb)
            </p>
          </div>

          {/* Example 2: Custom Inline Script */}
          <div className="bg-orange-50 border border-orange-200 rounded-lg p-6 mb-8">
            <h2 className="text-xl font-semibold text-orange-900 mb-3">
              Example 2: Custom Inline Script
            </h2>
            <p className="text-orange-800 mb-4">
              Using <code className="bg-orange-100 px-1 rounded">Script</code> component for custom JavaScript:
            </p>
            <pre className="bg-orange-100 text-orange-900 p-4 rounded text-xs overflow-x-auto">
{`import { Script } from '@/components/security';

<Script nonce={nonce} type="text/javascript">
  {\`console.log('CSP nonce demo loaded');\`}
</Script>`}
            </pre>
            <p className="text-orange-700 text-sm mt-3">
              ✅ Check browser console for "CSP nonce demo loaded" message
            </p>
          </div>

          {/* Example 3: Inline Styles */}
          <div className="bg-pink-50 border border-pink-200 rounded-lg p-6 mb-8">
            <h2 className="text-xl font-semibold text-pink-900 mb-3">
              Example 3: Inline Styles (Rare - Prefer Tailwind)
            </h2>
            <p className="text-pink-800 mb-4">
              Using <code className="bg-pink-100 px-1 rounded">InlineStyle</code> component:
            </p>
            <pre className="bg-pink-100 text-pink-900 p-4 rounded text-xs overflow-x-auto">
{`import { InlineStyle } from '@/components/security';

<InlineStyle nonce={nonce}>
  {\`.demo-custom { color: magenta; font-weight: bold; }\`}
</InlineStyle>`}
            </pre>
            <p className="demo-custom mt-3">
              ✅ This text uses the custom .demo-custom class
            </p>
          </div>

          {/* Security Properties */}
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 mb-8">
            <h2 className="text-xl font-semibold text-red-900 mb-3">
              🔒 Security Properties
            </h2>
            <ul className="list-disc list-inside space-y-2 text-red-800">
              <li>
                <strong>No unsafe-inline</strong>: CSP header does NOT contain 'unsafe-inline'
              </li>
              <li>
                <strong>Nonce-based allowlisting</strong>: Only scripts with valid nonce execute
              </li>
              <li>
                <strong>XSS Protection</strong>: Injected scripts without nonce are BLOCKED
              </li>
              <li>
                <strong>Unique per request</strong>: Nonce changes on every page load
              </li>
              <li>
                <strong>Crypto-random</strong>: Unpredictable to attackers (128+ bits entropy)
              </li>
            </ul>
          </div>

          {/* Test XSS (Should be BLOCKED) */}
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
            <h2 className="text-xl font-semibold text-yellow-900 mb-3">
              ⚠️ XSS Test (Should be BLOCKED)
            </h2>
            <p className="text-yellow-800 mb-4">
              Try adding this script WITHOUT a nonce (it should be blocked by CSP):
            </p>
            <pre className="bg-yellow-100 text-yellow-900 p-4 rounded text-xs">
{`<script>alert('XSS!');</script>`}
            </pre>
            <p className="text-yellow-700 text-sm mt-3">
              ❌ This script is NOT included because it would be blocked by CSP.
              If you inject it via browser DevTools, you'll see a CSP violation.
            </p>
          </div>
        </div>
      </div>

      {/* JSON-LD Scripts with Nonces */}
      <JsonLdScript nonce={nonce} data={organizationSchema} />
      <JsonLdScript nonce={nonce} data={breadcrumbSchema} />

      {/* Custom Inline Script with Nonce */}
      <Script nonce={nonce} type="text/javascript">
        {`console.log('✅ CSP Nonce Demo: Script executed successfully with nonce: ${nonce || 'N/A'}');`}
      </Script>

      {/* Inline Styles with Nonce */}
      <InlineStyle nonce={nonce}>
        {`.demo-custom {
          color: magenta;
          font-weight: bold;
          font-style: italic;
        }`}
      </InlineStyle>
    </div>
  );
}
