"use client";

/**
 * Email Sequences Page
 * Main page for managing email sequences
 */

import React, { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Plus, Sparkles, Library, BarChart3 } from "lucide-react";
import { SequenceList } from "@/components/sequences/SequenceList";
import { SequenceBuilder } from "@/components/sequences/SequenceBuilder";
import { SequenceStats } from "@/components/sequences/SequenceStats";
import { useToast } from "@/hooks/use-toast";

// Template data (would come from database in production)
const TEMPLATES = [
  {
    id: "saas-cold",
    name: "SaaS Cold Outreach",
    description: "5-step sequence for introducing your SaaS product to cold prospects",
    category: "saas",
    type: "cold_outreach",
    steps: 5,
    conversionRate: "3-5%",
  },
  {
    id: "ecom-cart",
    name: "Cart Abandonment",
    description: "3-step sequence to recover abandoned shopping carts",
    category: "ecommerce",
    type: "re_engagement",
    steps: 3,
    conversionRate: "15-20%",
  },
  {
    id: "service-nurture",
    name: "Service Lead Nurture",
    description: "7-step nurture sequence for service-based businesses",
    category: "service_business",
    type: "lead_nurture",
    steps: 7,
    conversionRate: "8-12%",
  },
  {
    id: "trial-conversion",
    name: "Trial to Paid",
    description: "4-step onboarding sequence for trial users",
    category: "trial_conversion",
    type: "onboarding",
    steps: 4,
    conversionRate: "20-30%",
  },
  {
    id: "customer-winback",
    name: "Win-Back Campaign",
    description: "3-step sequence to re-engage churned customers",
    category: "win_back",
    type: "re_engagement",
    steps: 3,
    conversionRate: "5-8%",
  },
  {
    id: "referral-request",
    name: "Referral Request",
    description: "3-step sequence asking happy customers for referrals",
    category: "referral",
    type: "custom",
    steps: 3,
    conversionRate: "10-15%",
  },
];

export default function SequencesPage() {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState("sequences");
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [templateDialogOpen, setTemplateDialogOpen] = useState(false);
  const [selectedSequence, setSelectedSequence] = useState<string | null>(null);

  // Mock data - would come from API in production
  const [sequences, setSequences] = useState([
    {
      _id: "seq1",
      name: "SaaS Product Launch",
      description: "Cold outreach for product launch",
      sequenceType: "cold_outreach",
      status: "active" as const,
      totalSteps: 5,
      metrics: {
        sent: 150,
        opened: 75,
        clicked: 30,
        replied: 12,
        converted: 5,
      },
      createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
      updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    },
  ]);

  const [formData, setFormData] = useState({
    name: "",
    sequenceType: "cold_outreach",
    goal: "",
    customInstructions: "",
  });

  const handleCreateSequence = async () => {
    try {
      // API call would go here
      toast({
        title: "Sequence Created",
        description: "Your email sequence is being generated by AI...",
      });
      setCreateDialogOpen(false);
      setFormData({
        name: "",
        sequenceType: "cold_outreach",
        goal: "",
        customInstructions: "",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to create sequence",
        variant: "destructive",
      });
    }
  };

  const handleUseTemplate = (templateId: string) => {
    // Create sequence from template
    toast({
      title: "Template Selected",
      description: "Creating sequence from template...",
    });
    setTemplateDialogOpen(false);
  };

  const handleStatusChange = (sequenceId: string, status: string) => {
    setSequences((prev) =>
      prev.map((seq) =>
        seq._id === sequenceId ? { ...seq, status: status as any } : seq
      )
    );
    toast({
      title: "Status Updated",
      description: `Sequence ${status === "active" ? "activated" : "paused"}`,
    });
  };

  const handleDuplicate = (sequenceId: string) => {
    toast({
      title: "Sequence Duplicated",
      description: "Creating a copy of this sequence...",
    });
  };

  const handleDelete = (sequenceId: string) => {
    setSequences((prev) => prev.filter((seq) => seq._id !== sequenceId));
    toast({
      title: "Sequence Deleted",
      description: "The sequence has been removed",
    });
  };

  const handleAnalyze = (sequenceId: string) => {
    setSelectedSequence(sequenceId);
    setActiveTab("analytics");
  };

  return (
    <div className="container mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Email Sequences</h1>
          <p className="text-muted-foreground">
            Create and manage automated email sequences
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Dialog open={templateDialogOpen} onOpenChange={setTemplateDialogOpen}>
            <DialogTrigger asChild>
              <Button variant="outline">
                <Library className="h-4 w-4 mr-2" />
                Templates
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>Sequence Templates</DialogTitle>
                <DialogDescription>
                  Choose from pre-built, high-converting email sequences
                </DialogDescription>
              </DialogHeader>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                {TEMPLATES.map((template) => (
                  <Card
                    key={template.id}
                    className="cursor-pointer hover:shadow-lg transition-shadow"
                    onClick={() => handleUseTemplate(template.id)}
                  >
                    <CardHeader>
                      <CardTitle className="text-lg">{template.name}</CardTitle>
                      <CardDescription>{template.description}</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-muted-foreground">
                          {template.steps} steps
                        </span>
                        <span className="font-medium text-green-600">
                          {template.conversionRate} conversion
                        </span>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </DialogContent>
          </Dialog>

          <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="h-4 w-4 mr-2" />
                Create Sequence
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New Sequence</DialogTitle>
                <DialogDescription>
                  Let AI generate a high-converting email sequence for you
                </DialogDescription>
              </DialogHeader>

              <div className="space-y-4 mt-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Sequence Name</Label>
                  <Input
                    id="name"
                    value={formData.name}
                    onChange={(e) =>
                      setFormData({ ...formData, name: e.target.value })
                    }
                    placeholder="e.g., SaaS Product Launch"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="type">Sequence Type</Label>
                  <Select
                    value={formData.sequenceType}
                    onValueChange={(value) =>
                      setFormData({ ...formData, sequenceType: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="cold_outreach">Cold Outreach</SelectItem>
                      <SelectItem value="lead_nurture">Lead Nurture</SelectItem>
                      <SelectItem value="onboarding">Onboarding</SelectItem>
                      <SelectItem value="re_engagement">Re-engagement</SelectItem>
                      <SelectItem value="custom">Custom</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="goal">Sequence Goal</Label>
                  <Textarea
                    id="goal"
                    value={formData.goal}
                    onChange={(e) =>
                      setFormData({ ...formData, goal: e.target.value })
                    }
                    placeholder="What do you want to achieve?"
                    rows={3}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="instructions">
                    Custom Instructions (Optional)
                  </Label>
                  <Textarea
                    id="instructions"
                    value={formData.customInstructions}
                    onChange={(e) =>
                      setFormData({
                        ...formData,
                        customInstructions: e.target.value,
                      })
                    }
                    placeholder="Any specific requirements or preferences?"
                    rows={3}
                  />
                </div>

                <Button
                  className="w-full"
                  onClick={handleCreateSequence}
                  disabled={!formData.name || !formData.goal}
                >
                  <Sparkles className="h-4 w-4 mr-2" />
                  Generate with AI
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Main Content */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="sequences">My Sequences</TabsTrigger>
          <TabsTrigger value="builder">Builder</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
        </TabsList>

        <TabsContent value="sequences" className="space-y-4">
          <SequenceList
            sequences={sequences}
            onSelect={(id) => {
              setSelectedSequence(id);
              setActiveTab("builder");
            }}
            onStatusChange={handleStatusChange}
            onDuplicate={handleDuplicate}
            onDelete={handleDelete}
            onAnalyze={handleAnalyze}
          />
        </TabsContent>

        <TabsContent value="builder" className="space-y-4">
          {selectedSequence ? (
            <SequenceBuilder
              sequence={sequences.find((s) => s._id === selectedSequence)}
              steps={[]} // Would load from API
              onSave={(data) => {
                toast({
                  title: "Sequence Updated",
                  description: "Your changes have been saved",
                });
              }}
              onAddStep={() => {
                toast({
                  title: "Step Added",
                  description: "New step added to sequence",
                });
              }}
              onUpdateStep={(stepId, data) => {
                toast({
                  title: "Step Updated",
                  description: "Changes saved successfully",
                });
              }}
              onRegenerateStep={(stepId) => {
                toast({
                  title: "Regenerating",
                  description: "AI is regenerating this step...",
                });
              }}
              onDeleteStep={(stepId) => {
                toast({
                  title: "Step Deleted",
                  description: "Step removed from sequence",
                });
              }}
              isEditing={true}
            />
          ) : (
            <Card>
              <CardContent className="flex flex-col items-center justify-center py-16">
                <p className="text-muted-foreground mb-4">
                  Select a sequence to edit
                </p>
                <Button onClick={() => setActiveTab("sequences")}>
                  View Sequences
                </Button>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="analytics" className="space-y-4">
          {selectedSequence ? (
            <SequenceStats
              sequence={sequences.find((s) => s._id === selectedSequence)!}
              stepMetrics={[
                {
                  stepNumber: 1,
                  stepName: "Initial Contact",
                  sent: 150,
                  openRate: 50,
                  clickRate: 20,
                  replyRate: 8,
                },
                {
                  stepNumber: 2,
                  stepName: "Value Addition",
                  sent: 135,
                  openRate: 45,
                  clickRate: 18,
                  replyRate: 6,
                },
              ]}
              recommendations={[
                {
                  type: "subject_line",
                  message:
                    "Step 2 has a lower open rate. Consider A/B testing different subject lines.",
                },
                {
                  type: "cta",
                  message:
                    "Add a more prominent CTA button in Step 1 to improve click rate.",
                },
              ]}
            />
          ) : (
            <Card>
              <CardContent className="flex flex-col items-center justify-center py-16">
                <BarChart3 className="h-12 w-12 text-muted-foreground mb-4" />
                <p className="text-muted-foreground mb-4">
                  Select a sequence to view analytics
                </p>
                <Button onClick={() => setActiveTab("sequences")}>
                  View Sequences
                </Button>
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
